/* AQA Combined Science Trilogy, Foundation tier, Biology content (B1-B7).
   Lessons and questions to be populated against the AQA 8464 specification. */
window.CONTENT_BIOLOGY = (function () {
  const topics = [
    { id: 'b1', code: 'B1', name: 'Cell biology', sub: 'Cell structure, transport, division' },
    { id: 'b2', code: 'B2', name: 'Organisation', sub: 'Tissues, digestion, blood, plants' },
    { id: 'b3', code: 'B3', name: 'Infection & response', sub: 'Pathogens, immunity, vaccines, drugs' },
    { id: 'b4', code: 'B4', name: 'Bioenergetics', sub: 'Photosynthesis and respiration' },
    { id: 'b5', code: 'B5', name: 'Homeostasis & response', sub: 'Nervous system, hormones, control' },
    { id: 'b6', code: 'B6', name: 'Inheritance, variation & evolution', sub: 'DNA, genetics, evolution' },
    { id: 'b7', code: 'B7', name: 'Ecology', sub: 'Ecosystems, biodiversity, human impact' }
  ];

  const lessons = {
    b1: {
      intro: "Every living thing is made of cells. Some organisms are just one cell (bacteria, yeast). You're made of trillions of them, organised into tissues and organs. This topic covers what cells look like inside, how they divide to make more of themselves, and how substances get in and out.",
      sections: [
        { h: "Eukaryotic and prokaryotic cells",
          body: ["There are two big categories of cell:",
                 "<ul><li><strong>Eukaryotic cells</strong> have a <strong>nucleus</strong> that holds the genetic material. Animal cells, plant cells, fungal cells and protist cells are all eukaryotic.</li><li><strong>Prokaryotic cells</strong> do NOT have a nucleus. Their genetic material floats freely in the cytoplasm, plus there are smaller loops called <strong>plasmids</strong>. Bacteria are prokaryotic.</li></ul>",
                 "Prokaryotic cells are much <strong>smaller</strong> than eukaryotic cells. They're also much simpler inside."],
          callout: { type: 'key', label: 'Quick rule', text: "If it has a nucleus, it's eukaryotic. If it doesn't, it's prokaryotic. Bacteria are the main prokaryote you need to know." } },
        { h: "Animal cells",
          body: ["All animal cells contain these parts:",
                 "<ul><li><strong>Nucleus</strong>, holds the DNA, controls the cell</li><li><strong>Cytoplasm</strong>, jelly-like fluid where chemical reactions happen</li><li><strong>Cell membrane</strong>, thin layer around the outside, controls what goes in and out</li><li><strong>Mitochondria</strong>, where aerobic respiration happens, releases energy</li><li><strong>Ribosomes</strong>, where proteins are made</li></ul>"] },
        { h: "Plant cells",
          body: ["Plant cells have everything animal cells have, PLUS three extras:",
                 "<ul><li><strong>Cell wall</strong>, made of cellulose, gives the cell strength and shape</li><li><strong>Chloroplasts</strong>, where photosynthesis happens, contain the green pigment chlorophyll</li><li><strong>Permanent vacuole</strong>, filled with cell sap, keeps the cell rigid (turgid)</li></ul>",
                 "Bacterial (prokaryotic) cells also have a cell wall, but it's not made of cellulose, so don't mix them up."] },
        { h: "Specialised cells",
          body: ["Different cells are <strong>specialised</strong> for different jobs. They have features that suit their function.",
                 "<ul><li><strong>Sperm cell:</strong> long tail to swim, lots of mitochondria for energy, enzymes in the head to penetrate the egg</li><li><strong>Nerve cell (neurone):</strong> very long axon to carry signals, branched dendrites to connect to other neurones</li><li><strong>Muscle cell:</strong> long, lots of mitochondria for energy to contract</li><li><strong>Root hair cell:</strong> long extension to maximise surface area for absorbing water and minerals</li><li><strong>Xylem cell:</strong> hollow, dead, lined with strong lignin, transports water up through plants</li><li><strong>Phloem cell:</strong> living, with sieve plates between cells, transports sugars around the plant</li></ul>"] },
        { h: "Microscopes",
          body: ["A <strong>light microscope</strong> can magnify up to about 2000 times and lets you see whole cells and the nucleus.",
                 "An <strong>electron microscope</strong> has much higher magnification (about 2 million times) and much better <strong>resolution</strong> (how clear the image is). Electron microscopes can show tiny structures like ribosomes and the internal detail of mitochondria.",
                 "<strong>Magnification formula:</strong>",
                 "<strong>magnification = image size &divide; real size</strong>",
                 "Watch your units. Image size is usually in mm. Real size is often in micrometres (&micro;m). 1 mm = 1000 &micro;m."] },
        { h: "Cell division (mitosis)",
          body: ["Body cells divide by <strong>mitosis</strong> to grow, repair damage and replace dead cells.",
                 "The full process is called the <strong>cell cycle</strong>:",
                 "<ul><li><strong>Growth and DNA replication</strong>, the cell grows, makes more sub-cellular parts and copies its DNA so each chromosome has an identical copy</li><li><strong>Mitosis</strong>, the copied chromosomes are pulled to opposite ends of the cell, then the nucleus splits</li><li><strong>Cytokinesis</strong>, the cytoplasm and cell membrane split, leaving two daughter cells</li></ul>",
                 "Each daughter cell is <strong>genetically identical</strong> to the parent cell."],
          callout: { type: 'warn', label: 'Common slip', text: "Mitosis makes IDENTICAL cells. Meiosis (which makes gametes) makes DIFFERENT cells. Foundation only needs mitosis, but don't confuse the names." } },
        { h: "Stem cells",
          body: ["<strong>Stem cells</strong> are cells that haven't specialised yet. They can divide and turn into any type of cell.",
                 "<ul><li><strong>Embryonic stem cells</strong>, from very early embryos, can become any cell type</li><li><strong>Adult stem cells</strong>, found in bone marrow for example, can become a limited range of cell types (mainly blood cells)</li><li><strong>Plant meristem cells</strong>, found in the growing tips of roots and shoots, can become any plant cell type and can be used to clone plants quickly</li></ul>",
                 "<strong>Possible medical uses:</strong> growing replacement organs, treating diabetes (insulin-producing cells), paralysis (nerve cells), and more.",
                 "<strong>Ethical issues:</strong> embryonic stem cells come from embryos, which some people believe is wrong. There's also a risk of cells being rejected or carrying viruses."] },
        { h: "Diffusion",
          body: ["<strong>Diffusion</strong> is the net movement of particles from a high concentration to a low concentration. They move down the <strong>concentration gradient</strong>.",
                 "It's passive, no energy needed. The particles just bounce around randomly and spread out.",
                 "<strong>Examples:</strong>",
                 "<ul><li>Oxygen diffuses from the air in your lungs into your blood</li><li>Carbon dioxide diffuses out of your blood into the air to be breathed out</li><li>Digested food diffuses from the gut into the blood</li></ul>",
                 "<strong>Factors that speed up diffusion:</strong> bigger concentration gradient, higher temperature, larger surface area."] },
        { h: "Osmosis",
          body: ["<strong>Osmosis</strong> is the movement of WATER through a partially permeable membrane, from a region of higher water concentration (dilute solution) to a region of lower water concentration (concentrated solution).",
                 "Think of it as diffusion but for water specifically.",
                 "<strong>Required practical:</strong> investigating osmosis in plant tissue (usually potato cylinders). You cut potato cubes or cylinders, weigh them, leave them in different concentrations of sugar or salt solution, then weigh them again. Cubes in dilute solution gain mass (water moves in), cubes in concentrated solution lose mass (water moves out)."],
          callout: { type: 'key', label: 'Osmosis vs diffusion', text: "Diffusion = any particles moving down a gradient. Osmosis = specifically WATER moving through a partially permeable membrane. Don't say 'water diffuses', say 'water moves by osmosis'." } },
        { h: "Active transport",
          body: ["<strong>Active transport</strong> moves substances AGAINST the concentration gradient, from low to high. Because this is uphill, it <strong>uses energy</strong> from respiration (so it needs mitochondria).",
                 "<strong>Examples:</strong>",
                 "<ul><li>Root hair cells absorb mineral ions from soil into the plant, even though the soil has a lower mineral concentration than the cell</li><li>The small intestine absorbs sugar from the gut into the blood, even when blood sugar is higher than gut sugar</li></ul>"] }
      ],
      keyPoints: [
        "Eukaryotic cells have a nucleus, prokaryotic cells don't",
        "Animal cells: nucleus, cytoplasm, cell membrane, mitochondria, ribosomes",
        "Plant cells have all that PLUS cell wall (cellulose), chloroplasts, permanent vacuole",
        "Specialised cells have features suited to their function (sperm, nerve, muscle, root hair, xylem, phloem)",
        "Light microscopes magnify up to ~2000x; electron microscopes magnify millions of times with better resolution",
        "Magnification = image size &divide; real size",
        "Mitosis produces two genetically identical daughter cells",
        "Stem cells are undifferentiated and can become other cell types",
        "Diffusion: passive movement of particles from high to low concentration",
        "Osmosis: water moving through a partially permeable membrane from dilute to concentrated",
        "Active transport: against the concentration gradient, uses energy from respiration"
      ],
      mistakes: [
        "Saying bacteria are eukaryotic, they're prokaryotic (no nucleus)",
        "Forgetting that plant cells have everything animal cells have plus extras (not 'instead of')",
        "Saying 'water diffuses' instead of 'water moves by osmosis'",
        "Forgetting that active transport needs energy (so cells doing lots of it have lots of mitochondria)",
        "Mixing up resolution and magnification, magnification just makes things bigger, resolution is the clarity"
      ]
    },

    b2: {
      intro: "Cells don't work alone. They group into tissues, tissues form organs, and organs work together as systems. This topic covers the digestive system, the heart and blood, plants' transport tissues, and how lifestyle affects health.",
      sections: [
        { h: "Levels of organisation",
          body: ["From smallest to biggest:",
                 "<ul><li><strong>Cells</strong> &rarr; the basic building block</li><li><strong>Tissues</strong> &rarr; groups of similar cells doing a job (e.g. muscle tissue)</li><li><strong>Organs</strong> &rarr; groups of tissues doing a function (e.g. the stomach)</li><li><strong>Organ systems</strong> &rarr; groups of organs working together (e.g. the digestive system)</li><li><strong>Organism</strong> &rarr; the whole thing (e.g. you)</li></ul>"] },
        { h: "Enzymes",
          body: ["<strong>Enzymes</strong> are biological catalysts. They're proteins. They speed up reactions in the body without being used up.",
                 "Each enzyme has a specific shape on its <strong>active site</strong>. Only one shape of substrate fits, like a key in a lock. This is called the <strong>lock and key model</strong>.",
                 "<strong>Conditions affect enzymes:</strong>",
                 "<ul><li>Higher temperature speeds reactions up, up to a point. Beyond the optimum (around 37&deg;C in humans), the enzyme starts to <strong>denature</strong>, the active site loses its shape and the substrate no longer fits.</li><li>Each enzyme has an optimum pH. Most body enzymes work best around pH 7. The stomach has pH ~2 and uses pepsin, which is optimised for acidic conditions.</li></ul>"],
          callout: { type: 'warn', label: 'Denatured, not killed', text: "Enzymes are not alive, so they can't 'die'. They get denatured, meaning the active site shape is destroyed. Say 'denatured' in the exam." } },
        { h: "The digestive system",
          body: ["Food is broken down by enzymes so the nutrients can be absorbed into the blood.",
                 "<strong>Three main groups of digestive enzymes:</strong>",
                 "<ul><li><strong>Carbohydrases</strong> (e.g. amylase) break down carbohydrates into sugars. Made in the salivary glands, pancreas and small intestine.</li><li><strong>Proteases</strong> break down proteins into amino acids. Made in the stomach, pancreas and small intestine.</li><li><strong>Lipases</strong> break down lipids (fats) into fatty acids and glycerol. Made in the pancreas and small intestine.</li></ul>",
                 "<strong>Bile</strong> is made in the liver and stored in the gall bladder. It does two jobs: it neutralises the acid from the stomach (so enzymes in the small intestine work properly), and it <strong>emulsifies</strong> fats (breaks fat droplets into smaller droplets, increasing surface area for lipase)."] },
        { h: "Food tests",
          body: ["<strong>Required practical:</strong> testing for sugars, starch, protein and lipids.",
                 "<ul><li><strong>Starch:</strong> add iodine. Goes from orange/brown to blue-black if starch present.</li><li><strong>Reducing sugars</strong> (glucose): add Benedict's solution and warm. Goes from blue to brick-red / orange if sugar present.</li><li><strong>Proteins:</strong> add biuret solution. Goes from blue to purple/lilac if protein present.</li><li><strong>Lipids:</strong> add ethanol then water. Cloudy white emulsion forms if lipid present.</li></ul>"] },
        { h: "Heart and circulation",
          body: ["The heart is a double pump made of muscle. It has four chambers:",
                 "<ul><li><strong>Right atrium</strong> &rarr; receives deoxygenated blood from the body</li><li><strong>Right ventricle</strong> &rarr; pumps blood to the lungs</li><li><strong>Left atrium</strong> &rarr; receives oxygenated blood from the lungs</li><li><strong>Left ventricle</strong> &rarr; pumps blood around the body</li></ul>",
                 "The left ventricle has a thicker wall than the right because it has to pump blood much further (around the whole body, not just to the lungs).",
                 "Three types of blood vessel:",
                 "<ul><li><strong>Arteries</strong> carry blood AWAY from the heart. Thick muscular walls to withstand high pressure.</li><li><strong>Capillaries</strong> are tiny, with one-cell-thick walls. Substances diffuse in and out here.</li><li><strong>Veins</strong> carry blood BACK to the heart. Thinner walls, wider lumen, have valves to stop backflow.</li></ul>"] },
        { h: "Blood",
          body: ["Blood has four main components:",
                 "<ul><li><strong>Red blood cells</strong>, carry oxygen, have no nucleus to fit more haemoglobin, are biconcave for surface area</li><li><strong>White blood cells</strong>, fight infection, have a nucleus</li><li><strong>Platelets</strong>, small cell fragments that help clotting</li><li><strong>Plasma</strong>, the liquid part, carries CO<sub>2</sub>, urea, hormones, digested food and antibodies</li></ul>"] },
        { h: "Treating heart problems",
          body: ["<strong>Coronary heart disease</strong>: the coronary arteries (which supply the heart muscle itself) get blocked by fatty deposits.",
                 "<strong>Treatments:</strong>",
                 "<ul><li><strong>Stents</strong>, small mesh tubes inserted to hold an artery open. Lets blood through. Good long-term solution, can be done with a small incision.</li><li><strong>Statins</strong>, drugs that lower bad cholesterol in the blood, slowing fatty deposits. Taken regularly, can have side effects.</li><li><strong>Heart transplants and artificial hearts</strong> for failing hearts. Major surgery, risk of rejection or infection.</li><li><strong>Pacemakers</strong>, small electronic devices to correct heart rhythm.</li></ul>"] },
        { h: "Health and disease",
          body: ["<strong>Health</strong> is a state of physical and mental wellbeing. It's affected by:",
                 "<ul><li>Diseases (communicable and non-communicable)</li><li>Diet, stress, exercise</li><li>Life circumstances</li></ul>",
                 "<strong>Risk factors</strong> increase the chance of getting a disease but don't guarantee it.",
                 "<ul><li><strong>Smoking</strong> increases risk of lung cancer, cardiovascular disease and lung disease</li><li><strong>Obesity</strong> increases risk of type 2 diabetes and cardiovascular disease</li><li><strong>Alcohol</strong> increases risk of liver disease and brain damage</li><li><strong>Carcinogens</strong> (including ionising radiation) increase cancer risk</li></ul>"] },
        { h: "Cancer",
          body: ["<strong>Cancer</strong> is caused by changes in cells that lead to uncontrolled growth and division. The resulting mass of cells is a <strong>tumour</strong>.",
                 "<ul><li><strong>Benign tumours</strong> stay in one place, contained. Not usually life-threatening.</li><li><strong>Malignant tumours</strong> invade other tissues, can spread through the blood to other parts of the body (this is called metastasis), and form secondary tumours. Malignant tumours ARE cancers.</li></ul>"] },
        { h: "Plant tissues and transport",
          body: ["Plants have organs too: leaves (photosynthesis), stems (support and transport), roots (water and mineral absorption).",
                 "<strong>Two transport tissues:</strong>",
                 "<ul><li><strong>Xylem</strong> carries water and minerals UP from roots to leaves. Made of dead, hollow, lignified cells. Movement is called <strong>transpiration</strong>.</li><li><strong>Phloem</strong> carries dissolved sugars (food) from leaves to the rest of the plant. Made of living cells with sieve plates. Movement is called <strong>translocation</strong>.</li></ul>",
                 "Transpiration is faster when it's hot, dry, windy or bright. Plants lose water through tiny holes called <strong>stomata</strong>, mostly on the underside of leaves. Each stoma is surrounded by two <strong>guard cells</strong> that open and close to control water loss."] }
      ],
      keyPoints: [
        "Cells &rarr; tissues &rarr; organs &rarr; organ systems &rarr; organism",
        "Enzymes are biological catalysts, proteins with a specific active site (lock and key)",
        "Enzymes denature above their optimum temperature or outside their optimum pH",
        "Carbohydrases break carbs to sugars, proteases break proteins to amino acids, lipases break lipids to fatty acids + glycerol",
        "Bile neutralises stomach acid and emulsifies fats (increases surface area for lipase)",
        "Food tests: iodine for starch (blue-black), Benedict's for sugar (brick red), biuret for protein (purple), ethanol for lipids (cloudy)",
        "Heart: right side &rarr; lungs, left side &rarr; body. Left ventricle has thicker walls",
        "Arteries away from heart, veins back to heart, capillaries are tiny for diffusion",
        "Red blood cells have no nucleus and are biconcave; plasma carries CO2, urea, hormones, antibodies",
        "Stents hold arteries open, statins lower cholesterol",
        "Xylem carries water up (dead, lignified, transpiration), phloem carries sugar around (living, sieve plates, translocation)",
        "Stomata in the leaf control water loss and gas exchange"
      ],
      mistakes: [
        "Saying enzymes are 'killed' at high temperatures, they get DENATURED",
        "Forgetting that bile is made in the liver but stored in the gall bladder",
        "Confusing arteries and veins, arteries carry blood AWAY from the heart",
        "Saying red blood cells have a nucleus, they don't, that's why they can fit more haemoglobin",
        "Mixing up xylem and phloem, xylem = water (up), phloem = food (around)"
      ]
    },

    b3: {
      intro: "Pathogens are microorganisms that cause disease. This topic covers how they spread, how your body defends itself, and how we use vaccines and drugs to fight them.",
      sections: [
        { h: "Types of pathogen",
          body: ["A <strong>pathogen</strong> is a microorganism that causes infectious (communicable) disease. Four main types:",
                 "<ul><li><strong>Bacteria</strong>, e.g. <em>Salmonella</em> (food poisoning), gonorrhoea</li><li><strong>Viruses</strong>, e.g. measles, HIV, tobacco mosaic virus (in plants)</li><li><strong>Fungi</strong>, e.g. rose black spot</li><li><strong>Protists</strong>, e.g. the malaria parasite</li></ul>",
                 "Bacteria and viruses both reproduce inside the host but in different ways. Bacteria multiply in body fluids and release toxins that damage cells. Viruses live inside cells, take them over to make copies, and then burst out, destroying the cell."] },
        { h: "Specific examples to learn",
          body: ["<strong>Measles</strong> (virus): spread by droplets in coughs and sneezes. Fever, red skin rash. Can be serious. Vaccine via the MMR jab.",
                 "<strong>HIV</strong> (virus): spread by sexual contact or exchange of body fluids. Attacks immune system. Late-stage HIV is called AIDS. Treated with antiretroviral drugs.",
                 "<strong>Tobacco mosaic virus (TMV)</strong>: plant disease. Causes a mosaic pattern of discolouration on leaves. Reduces photosynthesis and so yield.",
                 "<strong>Salmonella</strong> (bacteria): food poisoning. From raw or undercooked meat and poultry. Causes fever, vomiting, diarrhoea. UK farmers vaccinate chickens to reduce it.",
                 "<strong>Gonorrhoea</strong> (bacteria): sexually transmitted. Yellow/green discharge, painful urination. Was easily treated with penicillin until resistant strains appeared. Use barrier contraception (condoms) to prevent.",
                 "<strong>Rose black spot</strong> (fungus): purple/black spots on rose leaves. Spread by wind and water. Treated with fungicides or by removing affected leaves.",
                 "<strong>Malaria</strong> (protist): spread by mosquitoes (vector). Causes fever, can be fatal. Prevent by avoiding bites (mosquito nets, repellents) and by killing mosquitoes."] },
        { h: "Reducing the spread of disease",
          body: ["<ul><li><strong>Hygiene:</strong> hand washing, food hygiene, disinfecting surfaces</li><li><strong>Isolating infected people</strong> so they can't pass it on</li><li><strong>Destroying vectors</strong> like mosquitoes</li><li><strong>Vaccination</strong> against specific diseases</li></ul>"] },
        { h: "Body defences",
          body: ["Your body has three lines of defence against pathogens:",
                 "<strong>1. Stopping them getting in:</strong>",
                 "<ul><li>Skin is a physical barrier and produces antimicrobial substances</li><li>Nose hairs and mucus trap pathogens</li><li>Trachea and bronchi produce mucus, which is moved up by cilia (tiny hairs) to be swallowed</li><li>Stomach acid kills swallowed pathogens</li></ul>",
                 "<strong>2. White blood cells (if pathogens get in):</strong>",
                 "<ul><li><strong>Phagocytosis</strong>: white blood cells engulf and digest pathogens</li><li><strong>Antibody production</strong>: each pathogen has unique markers (antigens). White blood cells make antibodies that lock onto those antigens and destroy the pathogen.</li><li><strong>Antitoxin production</strong>: antitoxins neutralise toxins released by bacteria.</li></ul>"],
          callout: { type: 'key', label: 'Specific antibodies', text: "Each antibody fits ONE specific antigen, like enzyme and substrate. That's why you need a different antibody for every pathogen." } },
        { h: "Vaccination",
          body: ["A <strong>vaccine</strong> contains small amounts of dead or weakened pathogen.",
                 "When injected, your white blood cells make antibodies to it without you actually getting ill. If the real pathogen attacks later, your body can make antibodies <strong>quickly</strong>, so you don't get sick.",
                 "<strong>Herd immunity:</strong> if enough people are vaccinated, the pathogen can't spread easily, protecting people who can't be vaccinated (babies, the immunocompromised)."] },
        { h: "Antibiotics and painkillers",
          body: ["<strong>Antibiotics</strong> (e.g. penicillin) kill bacteria inside the body. They do NOT work on viruses, because viruses live inside our cells, and any drug strong enough to kill the virus would also damage the cell.",
                 "Specific bacteria need specific antibiotics. Misuse of antibiotics has led to <strong>antibiotic-resistant bacteria</strong> like MRSA. The bacteria mutate, the resistant ones survive treatment and reproduce, and you end up with a strain that the antibiotic can't kill.",
                 "<strong>Painkillers</strong> (e.g. paracetamol) treat the symptoms of a disease but don't kill the pathogen.",
                 "<strong>How to slow antibiotic resistance:</strong> doctors should only prescribe antibiotics when needed, and patients should finish the full course every time."] },
        { h: "New drugs",
          body: ["<strong>Where drugs come from:</strong>",
                 "<ul><li>Many traditional drugs were extracted from plants (e.g. digitalis from foxgloves) or microorganisms (penicillin from <em>Penicillium</em> mould)</li><li>Most new drugs are now synthesised by chemists, but the starting point often comes from a natural source</li></ul>",
                 "<strong>Stages of drug testing:</strong>",
                 "<ul><li><strong>Preclinical</strong>: tested on cells, tissues, then live animals. Checks for toxicity and effectiveness.</li><li><strong>Clinical trials on healthy volunteers</strong>: starts with very low doses, checks safety and side effects.</li><li><strong>Clinical trials on patients</strong>: finds the right dose, checks effectiveness. Uses a <strong>double-blind, placebo-controlled</strong> design where possible (neither the patient nor the doctor knows who got the real drug).</li></ul>"] }
      ],
      keyPoints: [
        "Pathogens come in four types: bacteria, viruses, fungi, protists",
        "Bacteria multiply and release toxins; viruses take over cells and burst them",
        "Spread is reduced by hygiene, isolation, killing vectors, vaccination",
        "Skin, mucus, cilia and stomach acid keep most pathogens out",
        "White blood cells use phagocytosis, antibodies and antitoxins to fight infection",
        "Vaccines contain dead or weakened pathogen, prepare white blood cells to respond fast",
        "Antibiotics kill bacteria, not viruses",
        "Antibiotic resistance comes from over-use and incomplete courses",
        "Drug testing: preclinical (cells, tissues, animals) then clinical trials on humans (healthy then patients)",
        "Clinical trials use double-blind, placebo-controlled designs to avoid bias"
      ],
      mistakes: [
        "Saying antibiotics work on viruses, they do NOT, only on bacteria",
        "Calling vaccines 'antibodies', they're actually the dead/weakened pathogen that makes you produce antibodies",
        "Forgetting to mention 'dead or weakened' when defining a vaccine",
        "Saying painkillers cure infections, they only treat symptoms",
        "Saying antibiotic resistance evolves in YOU, it evolves in the BACTERIA"
      ]
    }
  };
  const questions = [
    { id: 'b1-1', topic: 'b1', type: 'mcq', marks: 1,
      text: 'Which of the following is found in plant cells but NOT in animal cells?',
      options: ['Nucleus', 'Mitochondria', 'Chloroplast', 'Ribosome'],
      answer: 2,
      optionFeedback: [
        "Both animal and plant cells have a nucleus, so this isn't a plant-only feature.",
        "Both animal and plant cells have mitochondria, this is where respiration happens in all eukaryotes.",
        "Correct. Chloroplasts contain chlorophyll and carry out photosynthesis. Animals don't photosynthesise, so they don't need chloroplasts.",
        "Both animal and plant cells have ribosomes, this is where proteins are made."
      ],
      teach: "Plant cells have everything animal cells have, plus three extras: cell wall (cellulose), chloroplasts, and a permanent vacuole." },
    { id: 'b1-2', topic: 'b1', type: 'mcq', marks: 1,
      text: 'Which type of cell does NOT contain a nucleus?',
      options: ['Animal cell', 'Plant cell', 'Bacterial cell', 'Fungal cell'],
      answer: 2,
      optionFeedback: [
        "Animal cells are eukaryotic, they have a nucleus.",
        "Plant cells are eukaryotic, they have a nucleus.",
        "Correct. Bacteria are prokaryotic, their DNA floats freely in the cytoplasm rather than being inside a nucleus.",
        "Fungal cells are eukaryotic, they have a nucleus."
      ],
      teach: "Prokaryotic cells (bacteria) don't have a nucleus. Eukaryotic cells (animals, plants, fungi, protists) do." },
    { id: 'b1-3', topic: 'b1', type: 'mcq', marks: 1,
      text: 'What is the function of mitochondria in a cell?',
      options: ['Make proteins', 'Carry out aerobic respiration to release energy', 'Control the cell', 'Store water'],
      answer: 1,
      optionFeedback: [
        "Proteins are made by ribosomes, not mitochondria.",
        "Correct. Mitochondria are the site of aerobic respiration. Cells that need lots of energy (like muscle cells and sperm cells) have lots of mitochondria.",
        "The nucleus controls the cell, not the mitochondria.",
        "The permanent vacuole stores water and sap in plant cells, not mitochondria."
      ],
      teach: "Mitochondria = aerobic respiration = energy release. Cells doing energetic work have more of them." },
    { id: 'b1-4', topic: 'b1', type: 'mcq', marks: 1,
      text: 'A root hair cell has a long extension into the soil. What is this adaptation FOR?',
      options: ['To anchor the plant in place', 'To increase surface area for absorption', 'To store food', 'To photosynthesise'],
      answer: 1,
      optionFeedback: [
        "Anchoring is what bigger roots do, not the individual root hair cells.",
        "Correct. The long extension gives a large surface area, so more water and mineral ions can be absorbed at once.",
        "Food is stored in other parts of the plant, like the leaves or roots in general, not specifically in root hair cell extensions.",
        "Root hair cells are underground and have no chloroplasts, so they can't photosynthesise."
      ],
      teach: "Surface area matters whenever something needs to be absorbed or exchanged. Root hairs, lung alveoli and small intestine villi all use the same trick." },
    { id: 'b1-5', topic: 'b1', type: 'mcq', marks: 1,
      text: 'What is the correct order of the cell cycle?',
      options: ['Mitosis, growth, cytokinesis', 'Growth and DNA replication, mitosis, cytokinesis', 'Cytokinesis, mitosis, growth', 'DNA replication, cytokinesis, mitosis'],
      answer: 1,
      optionFeedback: [
        "Growth comes BEFORE mitosis, not after.",
        "Correct. First the cell grows and copies its DNA. Then mitosis splits the chromosomes. Finally cytokinesis splits the cytoplasm into two daughter cells.",
        "Cytokinesis is the LAST stage, the splitting of the cell into two.",
        "DNA replication happens first, mitosis comes next, then cytokinesis. The order's wrong here."
      ],
      teach: "Cell cycle order: grow + copy DNA, then mitosis (split nucleus), then cytokinesis (split the rest of the cell). Two identical daughter cells at the end." },
    { id: 'b1-6', topic: 'b1', type: 'mcq', marks: 1,
      text: 'Which process moves particles from high concentration to low concentration WITHOUT using energy?',
      options: ['Active transport', 'Diffusion', 'Mitosis', 'Respiration'],
      answer: 1,
      optionFeedback: [
        "Active transport DOES use energy and moves things AGAINST the gradient. Opposite of what the question asks.",
        "Correct. Diffusion is passive (no energy needed) and moves particles down their concentration gradient (high to low).",
        "Mitosis is cell division, not particle movement.",
        "Respiration releases energy from glucose, it's not a transport process."
      ],
      teach: "Diffusion = passive (no energy), high to low. Active transport = needs energy, low to high. The key word in this question is 'without using energy'." },
    { id: 'b1-7', topic: 'b1', type: 'mcq', marks: 1,
      text: 'A potato cylinder is left in a very concentrated salt solution for an hour. What will happen to its mass?',
      options: ['It will increase (gain mass)', 'It will decrease (lose mass)', 'It will stay the same', 'It will double'],
      answer: 1,
      optionFeedback: [
        "Water would move INTO the potato only if the solution were more dilute than the potato. A concentrated salt solution is more concentrated than the potato.",
        "Correct. The salt solution has a lower water concentration than the potato. Water leaves the potato by osmosis, so the potato loses mass.",
        "There IS a concentration difference, so water moves, so the mass changes.",
        "Doubling would only happen if a huge amount of water entered, which it won't in a concentrated salt solution."
      ],
      teach: "Osmosis: water moves from where it's dilute (lots of water) to where it's concentrated (less water). Concentrated salt solution = low water concentration = water leaves the potato = mass decreases." },
    { id: 'b1-8', topic: 'b1', type: 'mcq', marks: 1,
      text: 'Which type of microscope can be used to see the internal structure of mitochondria?',
      options: ['Light microscope', 'Hand lens', 'Electron microscope', 'Naked eye'],
      answer: 2,
      optionFeedback: [
        "A light microscope can show that mitochondria exist but not their internal detail, it doesn't have the resolution.",
        "A hand lens magnifies a few times, nowhere near enough for sub-cellular detail.",
        "Correct. Electron microscopes have much higher resolution than light microscopes, enough to see inside individual organelles like mitochondria.",
        "The naked eye can't even see whole cells, never mind structures inside them."
      ],
      teach: "Light microscope: see cells and the nucleus. Electron microscope: see inside organelles. The difference is resolution, not just magnification." },
    { id: 'b1-9', topic: 'b1', type: 'short', marks: 2,
      text: 'Describe the function of the cell membrane.',
      markScheme: 'Surrounds the cell / forms the boundary of the cell (1 mark). Controls what substances enter and leave the cell (1 mark).',
      teach: "Two-mark structure-and-function question, so two clear points: WHERE it is (around the cell), and WHAT it does (controls what goes in and out)." },
    { id: 'b1-10', topic: 'b1', type: 'short', marks: 3,
      text: 'A sperm cell has many mitochondria and a long tail. Explain how these adaptations help it carry out its function.',
      markScheme: 'Mitochondria release energy from respiration / produce ATP (1 mark). The tail uses this energy to swim / move towards the egg (1 mark). Long tail / swimming lets the sperm reach the egg to fertilise it (1 mark).',
      teach: "Specialised-cell explain questions need you to link the FEATURE to the JOB. Mitochondria release energy, energy powers the tail, tail makes the cell swim to the egg." },
    { id: 'b1-11', topic: 'b1', type: 'short', marks: 2,
      text: 'A microscope image shows a cell with a real width of 50 micrometres. The image of the cell is 25 millimetres wide. Calculate the magnification.',
      markScheme: 'Convert units: 25 mm = 25 000 &micro;m (1 mark). Magnification = 25 000 &divide; 50 = &times;500 (1 mark). Allow correct calculation with same units throughout.',
      teach: "Always make the units match before dividing. mm &times; 1000 = &micro;m. Then magnification = image size &divide; real size. No units on the answer, just a number with &times; in front." },
    { id: 'b1-12', topic: 'b1', type: 'short', marks: 2,
      text: 'Explain the difference between diffusion and active transport.',
      markScheme: 'Diffusion moves particles from high concentration to low concentration (with the gradient) / does not need energy (1 mark). Active transport moves particles from low concentration to high concentration (against the gradient) / needs energy from respiration (1 mark).',
      teach: "Compare-and-contrast questions need clear opposites. Diffusion is passive, downhill. Active transport is energetic, uphill. State both halves." },
    { id: 'b1-13', topic: 'b1', type: 'mcq', marks: 1,
      text: 'Which of these is a feature of stem cells?',
      options: ['They have already become specialised', 'They can divide and become different cell types', 'They are only found in plants', 'They cannot divide'],
      answer: 1,
      optionFeedback: [
        "Stem cells are UNspecialised, that's the whole point.",
        "Correct. Stem cells haven't yet become a specific cell type, and they can divide and turn into many different types of cell.",
        "Stem cells are found in animals too (embryonic and adult). Plant stem cells are in the meristem.",
        "Stem cells can divide, that's one of their defining features."
      ],
      teach: "Stem cells = undifferentiated + can divide + can become other cell types. Three properties, all three matter." },

    { id: 'b2-1', topic: 'b2', type: 'mcq', marks: 1,
      text: 'What is the correct order, from smallest to largest, of biological organisation?',
      options: ['Organ, tissue, cell, system, organism', 'Cell, tissue, organ, organ system, organism', 'Tissue, cell, organism, organ, system', 'Cell, organ, tissue, organism, system'],
      answer: 1,
      optionFeedback: [
        "Cells are smaller than tissues, organs come after tissues.",
        "Correct. Cell (smallest) &rarr; tissue &rarr; organ &rarr; organ system &rarr; organism (largest).",
        "Cells are smaller than tissues.",
        "Tissues come before organs."
      ],
      teach: "Cell, tissue, organ, organ system, organism. Each level is built from many of the previous level." },
    { id: 'b2-2', topic: 'b2', type: 'mcq', marks: 1,
      text: 'What happens when an enzyme is heated well above its optimum temperature?',
      options: ['It speeds up forever', 'It dies', 'It denatures and stops working', 'It turns into a different enzyme'],
      answer: 2,
      optionFeedback: [
        "It speeds up only until the optimum. Past that, it slows and stops.",
        "Enzymes aren't alive, so they can't die. The correct word is 'denature'.",
        "Correct. The active site loses its shape (denatures) so the substrate no longer fits. The enzyme stops working.",
        "Denatured enzymes don't transform into other enzymes, they just stop working."
      ],
      teach: "Past the optimum temperature, the heat distorts the active site. We call this denaturing. Use the right word in the exam." },
    { id: 'b2-3', topic: 'b2', type: 'mcq', marks: 1,
      text: 'Which enzyme breaks down proteins?',
      options: ['Amylase', 'Lipase', 'Protease', 'Maltase'],
      answer: 2,
      optionFeedback: [
        "Amylase breaks down starch into sugar, not protein.",
        "Lipase breaks down lipids (fats) into fatty acids and glycerol.",
        "Correct. Protease breaks down proteins into amino acids. The name's a clue, 'prote-' for protein.",
        "Maltase breaks down maltose (a sugar), not protein."
      ],
      teach: "Carbohydrases &rarr; sugars. Proteases &rarr; amino acids. Lipases &rarr; fatty acids + glycerol. Match the enzyme name to its substrate." },
    { id: 'b2-4', topic: 'b2', type: 'mcq', marks: 1,
      text: 'What is the function of bile?',
      options: ['Digests starch', 'Neutralises stomach acid and emulsifies fats', 'Carries oxygen around the body', 'Stores excess sugar'],
      answer: 1,
      optionFeedback: [
        "Bile contains no enzymes, so it doesn't digest anything itself.",
        "Correct. Bile neutralises the acid coming from the stomach so enzymes in the small intestine can work, and it emulsifies fats (breaks them into smaller droplets, giving lipase a bigger surface area).",
        "That's red blood cells, not bile.",
        "That's the liver storing glycogen, a different function."
      ],
      teach: "Bile = made in liver, stored in gall bladder. Two jobs: NEUTRALISE acid and EMULSIFY fats. Doesn't actually digest anything." },
    { id: 'b2-5', topic: 'b2', type: 'mcq', marks: 1,
      text: 'You add iodine to an unknown food sample and it turns blue-black. What does the sample contain?',
      options: ['Sugar', 'Starch', 'Protein', 'Lipid'],
      answer: 1,
      optionFeedback: [
        "Sugar is tested with Benedict's, which goes brick-red, not iodine.",
        "Correct. Iodine + starch goes blue-black. If there's no starch, iodine stays orange/brown.",
        "Protein is tested with biuret, which goes purple.",
        "Lipid is tested with ethanol, which gives a cloudy emulsion."
      ],
      teach: "Iodine = starch (blue-black). Benedict's = sugar (brick red). Biuret = protein (purple). Ethanol = lipid (cloudy)." },
    { id: 'b2-6', topic: 'b2', type: 'mcq', marks: 1,
      text: 'Which side of the heart pumps blood to the lungs?',
      options: ['Left side', 'Right side', 'Top', 'Bottom'],
      answer: 1,
      optionFeedback: [
        "The left side pumps to the rest of the body, not the lungs. That's why its wall is thicker.",
        "Correct. The right side receives deoxygenated blood from the body and pumps it to the lungs to pick up oxygen.",
        "'Top' isn't a side of the heart, it's the atria region.",
        "'Bottom' isn't a side of the heart."
      ],
      teach: "Right side &rarr; lungs (less distance). Left side &rarr; whole body (more distance, thicker walls)." },
    { id: 'b2-7', topic: 'b2', type: 'mcq', marks: 1,
      text: 'Why do arteries have thicker walls than veins?',
      options: ['They carry more blood', 'They contain blood at high pressure from the heart', 'They are nearer the surface of the body', 'They have valves'],
      answer: 1,
      optionFeedback: [
        "Volume isn't the issue, pressure is.",
        "Correct. Arteries take blood directly from the heart, so the blood is under high pressure. Thick muscular walls stop them bursting.",
        "Arteries are usually deeper in the body than veins, not nearer the surface.",
        "VEINS have valves, not arteries. Veins need valves because blood pressure is lower."
      ],
      teach: "Arteries: high pressure &rarr; thick walls. Veins: low pressure &rarr; thinner walls with valves to stop backflow." },
    { id: 'b2-8', topic: 'b2', type: 'mcq', marks: 1,
      text: 'Red blood cells have no nucleus. Why is this an advantage?',
      options: ['It makes them lighter', 'There is more space for haemoglobin to carry oxygen', 'It stops them dividing', 'It makes them invisible'],
      answer: 1,
      optionFeedback: [
        "Mass isn't the point.",
        "Correct. No nucleus means more room inside the cell for the oxygen-carrying protein, haemoglobin. The cell can carry more oxygen per cell.",
        "Red blood cells don't divide anyway, that's a side effect, not the function.",
        "They aren't invisible, they make blood red."
      ],
      teach: "No nucleus = more haemoglobin = more oxygen carried. The biconcave disc shape also gives a bigger surface area for diffusion." },
    { id: 'b2-9', topic: 'b2', type: 'short', marks: 2,
      text: 'Describe the function of xylem in a plant.',
      markScheme: 'Transports water (and dissolved mineral ions) (1 mark) from the roots up to the leaves / rest of the plant (1 mark).',
      teach: "Two marks, so two parts: WHAT it carries (water and minerals) and the DIRECTION (up from roots to leaves). Both ideas needed." },
    { id: 'b2-10', topic: 'b2', type: 'short', marks: 3,
      text: 'Explain why lipase works faster after bile has been added to fat.',
      markScheme: 'Bile emulsifies fat / breaks fat into smaller droplets (1 mark). This increases the surface area of the fat (1 mark). So lipase has more area to work on / more enzyme-substrate collisions, speeding up the reaction (1 mark).',
      teach: "Surface area is the link. Emulsify &rarr; smaller droplets &rarr; bigger surface area &rarr; faster reaction. Same pattern as smashing a solid into a powder for chemistry rate questions." },
    { id: 'b2-11', topic: 'b2', type: 'short', marks: 2,
      text: 'A patient has a partially blocked coronary artery. State one treatment a doctor might recommend, and explain how it works.',
      markScheme: 'Any one treatment with a matching explanation. Stent: a metal mesh tube inserted to hold the artery open and let blood through (1 mark). OR statins: drugs taken regularly that lower cholesterol in the blood, slowing fatty deposit build-up (1 mark). The treatment named (1 mark), the mechanism (1 mark).',
      teach: "Stents = open the artery up. Statins = reduce cholesterol. Pick one and explain how it actually helps. Don't just name it." },
    { id: 'b2-12', topic: 'b2', type: 'mcq', marks: 1,
      text: 'Which of these is a non-communicable disease?',
      options: ['Measles', 'Salmonella food poisoning', 'Type 2 diabetes', 'Malaria'],
      answer: 2,
      optionFeedback: [
        "Measles is caused by a virus and is contagious, so it's communicable.",
        "Salmonella is caused by bacteria in food, so it's communicable.",
        "Correct. Type 2 diabetes is linked to lifestyle (diet, weight, exercise) and isn't passed from person to person.",
        "Malaria is caused by a protist and spread by mosquitoes, so it's communicable."
      ],
      teach: "Communicable = can be caught (caused by pathogens). Non-communicable = lifestyle / genetic / age-related, can't be caught." },
    { id: 'b2-13', topic: 'b2', type: 'short', marks: 2,
      text: 'Explain how a malignant tumour is different from a benign tumour.',
      markScheme: 'A malignant tumour can invade neighbouring tissues / spread through the blood to form secondary tumours elsewhere (1 mark). A benign tumour stays in one place and does not spread (1 mark).',
      teach: "Benign = stays put. Malignant = spreads (and is what we mean by cancer). The spreading via blood is called metastasis." },

    { id: 'b3-1', topic: 'b3', type: 'mcq', marks: 1,
      text: 'Which of these is NOT a type of pathogen?',
      options: ['Bacteria', 'Virus', 'Antibody', 'Fungus'],
      answer: 2,
      optionFeedback: [
        "Bacteria can be pathogens (e.g. Salmonella).",
        "Viruses are pathogens (e.g. measles, HIV).",
        "Correct. Antibodies are proteins your IMMUNE SYSTEM makes to fight pathogens. They aren't pathogens themselves.",
        "Fungi can be pathogens (e.g. rose black spot in plants)."
      ],
      teach: "Four pathogen types: bacteria, viruses, fungi, protists. Antibodies are how YOU fight pathogens, not a type of pathogen." },
    { id: 'b3-2', topic: 'b3', type: 'mcq', marks: 1,
      text: 'How do bacteria typically make you ill?',
      options: ['They take over your cells and make copies', 'They multiply and release toxins that damage cells', 'They digest your nutrients', 'They are too big to be removed'],
      answer: 1,
      optionFeedback: [
        "That's how viruses work, not bacteria. Bacteria reproduce in body fluids, not inside our cells.",
        "Correct. Bacteria divide rapidly in body fluids and release toxins. The toxins damage cells and cause the symptoms.",
        "Bacteria don't generally compete for our food in a way that makes us ill.",
        "Size isn't the issue."
      ],
      teach: "Bacteria: multiply in body fluids, release toxins. Viruses: live inside cells, take them over to make copies, burst out. Different mechanisms." },
    { id: 'b3-3', topic: 'b3', type: 'mcq', marks: 1,
      text: 'How is the measles virus spread?',
      options: ['Body fluids during sexual contact', 'Droplets when an infected person coughs or sneezes', 'Eating contaminated food', 'Mosquito bites'],
      answer: 1,
      optionFeedback: [
        "That's how HIV spreads, not measles.",
        "Correct. Measles is highly contagious and spreads through droplets in the air from coughs and sneezes.",
        "Salmonella is foodborne, not measles.",
        "Malaria is mosquito-spread, not measles."
      ],
      teach: "Measles &rarr; airborne droplets. HIV &rarr; body fluids. Salmonella &rarr; contaminated food. Malaria &rarr; mosquito vectors. Match each pathogen to its route." },
    { id: 'b3-4', topic: 'b3', type: 'mcq', marks: 1,
      text: 'How do mosquitoes act in the spread of malaria?',
      options: ['They cause the disease themselves', 'They are vectors that pass on the malaria parasite', 'They make you weaker so you catch malaria', 'They are infected but cannot pass it on'],
      answer: 1,
      optionFeedback: [
        "Mosquitoes don't cause malaria themselves, a protist does. The mosquito just transmits it.",
        "Correct. A vector is an organism that spreads a disease without being the cause. Mosquitoes bite an infected person, pick up the parasite, then bite someone else and pass it on.",
        "Making you weaker isn't how mosquitoes spread malaria.",
        "They CAN and DO pass it on, that's the whole point of being a vector."
      ],
      teach: "Vector = organism that carries a pathogen between hosts. Mosquito for malaria. The mosquito isn't ill itself, it's just a courier." },
    { id: 'b3-5', topic: 'b3', type: 'mcq', marks: 1,
      text: 'Which of these is the FIRST line of defence against pathogens?',
      options: ['Antibodies in the blood', 'Skin, mucus and stomach acid', 'White blood cells', 'Painkillers'],
      answer: 1,
      optionFeedback: [
        "Antibodies are inside the body, so by the time they're involved, the pathogen has already got in.",
        "Correct. The skin, mucus in the airways, cilia, and stomach acid all stop pathogens entering or kill them before they can do harm. These are the body's first line of defence.",
        "White blood cells fight pathogens that have already got in, so they're the second line, not the first.",
        "Painkillers don't fight pathogens at all, they just hide symptoms."
      ],
      teach: "First line: stop pathogens getting in (skin, mucus, acid, cilia). Second line: white blood cells (phagocytosis, antibodies, antitoxins) once they're in." },
    { id: 'b3-6', topic: 'b3', type: 'mcq', marks: 1,
      text: 'Which of the following correctly describes how a vaccine works?',
      options: ['It kills any pathogens already in your body', 'It contains dead or weakened pathogen so your white blood cells learn to respond', 'It cures all symptoms instantly', 'It is the same as taking an antibiotic'],
      answer: 1,
      optionFeedback: [
        "Vaccines don't kill existing infection, they prepare you in advance.",
        "Correct. The dead/weakened pathogen triggers white blood cells to make matching antibodies. Next time you meet the real one, you can produce antibodies fast enough to stop you getting sick.",
        "Vaccines are preventive, not symptomatic.",
        "Antibiotics treat existing bacterial infections. Vaccines prevent diseases (often viral). Different things."
      ],
      teach: "Vaccine = dead/weakened pathogen &rarr; antibodies made now &rarr; quick response if the real pathogen turns up later." },
    { id: 'b3-7', topic: 'b3', type: 'mcq', marks: 1,
      text: 'Why do antibiotics NOT work against viral infections?',
      options: ['Viruses are too small to be hit by antibiotics', 'Viruses live inside body cells, and the antibiotic would damage the cell too', 'Antibiotics are only for plants', 'Viruses cannot be treated at all'],
      answer: 1,
      optionFeedback: [
        "Size isn't really the issue.",
        "Correct. Antibiotics target features unique to bacteria. Viruses hide inside your own cells, so any drug strong enough to kill the virus would also damage the cell.",
        "Antibiotics are used in humans and animals.",
        "Antiviral drugs do exist, just not antibiotics."
      ],
      teach: "Antibiotics work on bacteria, not viruses. Antiviral drugs exist but they're different. Don't say 'take some antibiotics for your cold'." },
    { id: 'b3-8', topic: 'b3', type: 'mcq', marks: 1,
      text: 'In a clinical trial, what is a placebo?',
      options: ['The active drug being tested', 'A higher-dose version of the drug', 'A substance with no active ingredients given for comparison', 'A vitamin tablet'],
      answer: 2,
      optionFeedback: [
        "That's the drug being tested, not the placebo.",
        "A placebo is the opposite, it has no active ingredient at all.",
        "Correct. A placebo looks like the drug but has no active ingredient. It controls for the 'placebo effect' where people feel better just because they think they got a drug.",
        "A vitamin tablet isn't a placebo, it does have active ingredients."
      ],
      teach: "Placebo = looks like the drug, isn't the drug. Comparing the two groups shows whether the drug itself works, beyond the patient's belief that they're being treated." },
    { id: 'b3-9', topic: 'b3', type: 'short', marks: 2,
      text: 'Explain how white blood cells defend the body using antibodies.',
      markScheme: 'White blood cells produce antibodies (1 mark). Each antibody is specific / locks onto the antigens on a particular pathogen, which marks it for destruction / clumps pathogens together (1 mark).',
      teach: "Antibodies are SPECIFIC to one pathogen's antigens. Lock and key idea. They mark the pathogen for destruction." },
    { id: 'b3-10', topic: 'b3', type: 'short', marks: 3,
      text: 'Explain why a person who has been vaccinated against measles is unlikely to become ill if they later meet the real measles virus.',
      markScheme: 'The vaccine caused their white blood cells to produce antibodies against measles (1 mark). The body now has memory cells, so on second exposure antibodies can be produced quickly / in large amounts (1 mark). This destroys the virus before it can multiply enough to cause illness (1 mark).',
      teach: "Vaccination &rarr; antibodies made &rarr; memory &rarr; rapid response next time &rarr; no illness. All four ideas, three marks here." },
    { id: 'b3-11', topic: 'b3', type: 'short', marks: 2,
      text: 'Explain how the misuse of antibiotics can lead to antibiotic-resistant strains of bacteria.',
      markScheme: 'In a population of bacteria, a few have random mutations that make them resistant to the antibiotic (1 mark). When antibiotics kill the non-resistant ones, the resistant ones survive and reproduce, so the next generation is mostly resistant (1 mark).',
      teach: "Natural selection in real time. Random mutation &rarr; resistance &rarr; antibiotic kills the rest &rarr; resistant survive and breed &rarr; resistant population." },
    { id: 'b3-12', topic: 'b3', type: 'mcq', marks: 1,
      text: 'Which of these would help slow the spread of antibiotic resistance?',
      options: ['Prescribing antibiotics for every infection', 'Stopping the course as soon as you feel better', 'Doctors only prescribing antibiotics when needed and patients finishing the full course', 'Sharing antibiotics with friends'],
      answer: 2,
      optionFeedback: [
        "More antibiotic use means more selection pressure for resistant strains. Bad idea.",
        "Stopping early lets the strongest bacteria survive and multiply, the resistance gets worse.",
        "Correct. Only using antibiotics when actually needed, and finishing the course so all bacteria are killed, slows the build-up of resistance.",
        "Sharing antibiotics means people getting the wrong drug at the wrong dose, which makes resistance worse."
      ],
      teach: "Two rules: don't use antibiotics when you don't need them, and always finish the course. Both reduce selection pressure on resistant bacteria." },
    { id: 'b3-13', topic: 'b3', type: 'mcq', marks: 1,
      text: 'Which of these is NOT a stage in testing a new drug?',
      options: ['Preclinical testing on cells and tissues', 'Testing on healthy volunteers', 'Testing on patients with the disease', 'Skipping straight to selling it in shops'],
      answer: 3,
      optionFeedback: [
        "This IS a stage, the first one. Pre-clinical testing checks for toxicity before any humans are involved.",
        "Healthy volunteers are tested early to check safety and side effects.",
        "Patients with the disease are tested later to check effectiveness.",
        "Correct. Drugs are not sold without going through proper testing. Doing so would be illegal and dangerous."
      ],
      teach: "Order of testing: preclinical (cells, tissues, animals), then healthy volunteers, then patients. No skipping stages." }
  ];

  return { topics, lessons, questions };
})();
