/* AQA Combined Science Trilogy, Foundation tier, Chemistry content (C1-C10). */
window.CONTENT_CHEMISTRY = (function () {
  const topics = [
    { id: 'c1', code: 'C1', name: 'Atomic structure & periodic table', sub: 'Atoms, elements, electron shells, groups' },
    { id: 'c2', code: 'C2', name: 'Bonding & properties of matter', sub: 'Ionic, covalent and metallic bonding' },
    { id: 'c3', code: 'C3', name: 'Quantitative chemistry', sub: 'Relative formula mass, balancing equations' },
    { id: 'c4', code: 'C4', name: 'Chemical changes', sub: 'Acids, alkalis, reactivity, electrolysis' },
    { id: 'c5', code: 'C5', name: 'Energy changes', sub: 'Exothermic and endothermic reactions' },
    { id: 'c6', code: 'C6', name: 'Rate of reaction', sub: 'Speed of reactions, catalysts' },
    { id: 'c7', code: 'C7', name: 'Organic chemistry', sub: 'Crude oil, hydrocarbons, combustion' },
    { id: 'c8', code: 'C8', name: 'Chemical analysis', sub: 'Pure substances, chromatography' },
    { id: 'c9', code: 'C9', name: 'Chemistry of the atmosphere', sub: 'Greenhouse gases, climate change' },
    { id: 'c10', code: 'C10', name: 'Using resources', sub: 'Water, recycling, sustainability' }
  ];

  const lessons = {
    c1: {
      intro: "Everything around you is made of atoms. They're so small you can't see them, even with a normal microscope. But once you understand how they're built, the rest of chemistry starts to fall into place. This topic covers what atoms are made of, how they're arranged on the periodic table, and why elements in the same group behave alike.",
      sections: [
        { h: "What is an atom?",
          body: ["An atom is the smallest part of an element. Atoms are tiny: about 0.1 nanometres across (that's 0.0000001 mm). Despite being so small, they have an even smaller part in the middle called the <strong>nucleus</strong>. Around the nucleus, in regions called <strong>shells</strong> (or energy levels), are <strong>electrons</strong>.",
                 "Most of the atom is actually empty space. The nucleus is about 10,000 times smaller than the whole atom, but it contains almost all the mass."] },
        { h: "The three subatomic particles",
          body: ["Atoms are made of three smaller particles. Learn this table, examiners love testing it."],
          table: [["Particle","Where it is","Relative charge","Relative mass"],
                  ["Proton","Nucleus","+1","1"],
                  ["Neutron","Nucleus","0","1"],
                  ["Electron","Shells around nucleus","-1","Very small (about 1/2000)"]],
          afterBody: ["An atom has <strong>no overall charge</strong> because the number of protons equals the number of electrons. The +1 charges cancel the -1 charges exactly."] },
        { h: "Atomic number and mass number",
          body: ["Look at any element on the periodic table and you'll see two numbers next to its symbol:",
                 "<strong>Atomic number</strong> (the smaller one) = number of protons. This is what defines an element. All carbon atoms have 6 protons. Always.",
                 "<strong>Mass number</strong> (the bigger one) = number of protons + number of neutrons.",
                 "To find the number of neutrons: <strong>mass number minus atomic number</strong>.",
                 "Example: Sodium (Na) has atomic number 11 and mass number 23. So it has 11 protons, 11 electrons, and 23 minus 11 = 12 neutrons."] },
        { h: "Isotopes",
          body: ["Most elements come in different versions called <strong>isotopes</strong>. Isotopes have the SAME number of protons but DIFFERENT numbers of neutrons.",
                 "Example: Carbon-12 has 6 protons and 6 neutrons. Carbon-14 has 6 protons and 8 neutrons. Both are carbon (same number of protons) but they have different mass numbers."],
          callout: { type: 'key', label: 'Remember', text: "Same element = same atomic number = same number of protons. Isotopes differ in the number of neutrons, which means they differ in mass number." } },
        { h: "Electrons in shells",
          body: ["Electrons sit in shells around the nucleus. Each shell holds a limited number:",
                 "<ul><li>First shell: holds up to 2 electrons</li><li>Second shell: holds up to 8 electrons</li><li>Third shell: holds up to 8 electrons (for the elements you need to know)</li></ul>",
                 "Fill the shells in order from inside out. Sodium has 11 electrons total, so its arrangement is 2,8,1. (Two in the first, eight in the second, one in the third.)",
                 "The <strong>outer shell</strong> is the most important for chemistry. The number of electrons in the outer shell tells you which <strong>group</strong> on the periodic table the element is in."] },
        { h: "The periodic table",
          body: ["The periodic table is arranged in rows (called <strong>periods</strong>) and columns (called <strong>groups</strong>).",
                 "Elements in the same group have the <strong>same number of electrons in their outer shell</strong>. That's why they react in similar ways.",
                 "<ul><li>Group 1 elements have 1 outer electron</li><li>Group 2 have 2 outer electrons</li><li>Group 7 have 7 outer electrons</li><li>Group 0 have a full outer shell</li></ul>",
                 "Metals are on the left and centre of the table. Non-metals are on the right (with a zigzag line separating them)."] },
        { h: "Group 1: the alkali metals",
          body: ["Lithium, sodium, potassium and the others. They all have 1 outer electron.",
                 "They react by <strong>losing</strong> that outer electron to form a +1 ion (like Na+).",
                 "<strong>Going DOWN Group 1, reactivity INCREASES.</strong> Why? Going down, each element has more shells. The outer electron is further from the nucleus and the nucleus's pull on it is weaker. So the outer electron is lost more easily. Easier to lose = more reactive."] },
        { h: "Group 7: the halogens",
          body: ["Fluorine, chlorine, bromine, iodine. They have 7 outer electrons, one short of a full shell.",
                 "They react by <strong>gaining</strong> one electron to form a -1 ion (like Cl-).",
                 "<strong>Going DOWN Group 7, reactivity DECREASES.</strong> Why? The outer shell is further from the nucleus. It's harder for the nucleus to attract a new electron in. Harder to gain = less reactive."],
          callout: { type: 'warn', label: 'Easy to mix up', text: "Group 1 reactivity INCREASES going down. Group 7 reactivity DECREASES going down. They go in opposite directions. Learn it." } },
        { h: "Group 0: the noble gases",
          body: ["Helium, neon, argon, krypton, xenon. They have a <strong>full outer shell</strong> (helium has 2, the others have 8).",
                 "A full outer shell means they're stable. They don't need to gain or lose electrons. So they don't react with anything.",
                 "Argon is used in light bulbs and helium fills party balloons because they won't catch fire or react with what's around them."] }
      ],
      keyPoints: [
        "Protons have +1 charge, neutrons have no charge, electrons have -1 charge",
        "Atomic number = number of protons. Mass number = protons + neutrons",
        "Atoms have no overall charge because protons and electrons balance",
        "Isotopes are atoms of the same element with different numbers of neutrons",
        "Electrons fill shells in order: 2, then 8, then 8",
        "The group number tells you the number of outer electrons",
        "Group 1 metals lose 1 electron, Group 7 non-metals gain 1 electron",
        "Group 1: reactivity INCREASES down the group",
        "Group 7: reactivity DECREASES down the group",
        "Group 0 (noble gases) are unreactive because they have full outer shells"
      ],
      mistakes: [
        "Mixing up atomic number with mass number, atomic is protons only",
        "Forgetting that Group 1 reactivity goes UP but Group 7 goes DOWN",
        "Calling isotopes 'different elements', they're the same element with different mass",
        "Saying noble gases are reactive, they're inert (unreactive)"
      ]
    },

    c2: {
      intro: "Bonding is about what holds atoms together. There are three main types: ionic, covalent, and metallic. Understanding bonding explains why salt is a hard crystal, why water is a liquid, and why metals conduct electricity.",
      sections: [
        { h: "Why do atoms bond?",
          body: ["Atoms are most stable when they have a <strong>full outer shell</strong> of electrons (like the noble gases).",
                 "All other atoms react and bond to try to achieve a full outer shell. They can do this in three ways:",
                 "<ul><li><strong>Ionic bonding:</strong> One atom gives electrons to another (metal + non-metal)</li><li><strong>Covalent bonding:</strong> Atoms share electrons (non-metal + non-metal)</li><li><strong>Metallic bonding:</strong> Metal atoms share their outer electrons in a 'sea' (metal + metal)</li></ul>"] },
        { h: "Ionic bonding",
          body: ["Ionic bonds form between a <strong>metal</strong> and a <strong>non-metal</strong>.",
                 "The metal atom <strong>loses</strong> its outer electrons (becoming a positive ion). The non-metal atom <strong>gains</strong> those electrons (becoming a negative ion).",
                 "The positive and negative ions are then attracted to each other. This electrostatic attraction is the ionic bond.",
                 "Example: Sodium chloride (NaCl). Sodium loses 1 electron to become Na+. Chlorine gains 1 electron to become Cl-. The Na+ and Cl- ions attract each other."] },
        { h: "Properties of ionic compounds",
          body: ["Ionic compounds form <strong>giant ionic lattices</strong>, regular 3D arrangements of millions of positive and negative ions.",
                 "<strong>High melting and boiling points.</strong> There are strong electrostatic forces between the ions in the lattice. Lots of energy is needed to break these forces, so the melting point is high.",
                 "<strong>Conduct electricity when molten or dissolved, but not when solid.</strong> Electricity needs charged particles that can move. In a solid lattice, the ions are fixed in place. When melted or dissolved, the ions can move freely and carry charge.",
                 "<strong>Often soluble in water.</strong>"] },
        { h: "Covalent bonding",
          body: ["Covalent bonds form between <strong>non-metal atoms</strong>. The atoms <strong>share</strong> a pair of electrons.",
                 "Each shared pair counts as one covalent bond. Some molecules have single bonds, some have double or triple bonds.",
                 "Examples: H2 (hydrogen molecule), H2O (water), CO2 (carbon dioxide), CH4 (methane)."] },
        { h: "Simple molecular substances",
          body: ["Small molecules like water, oxygen and methane have:",
                 "<ul><li><strong>Strong covalent bonds INSIDE the molecules</strong></li><li><strong>Weak forces BETWEEN the molecules</strong> (called intermolecular forces)</li></ul>",
                 "When you melt or boil a simple molecular substance, you only need to overcome the WEAK forces between molecules. The covalent bonds inside the molecules don't break.",
                 "This is why simple molecular substances have <strong>low melting and boiling points</strong>. They don't conduct electricity because there are no charged particles."],
          callout: { type: 'warn', label: "Don't get caught out", text: "The covalent bonds inside a molecule are STRONG. The forces BETWEEN molecules are weak. Many students lose marks by saying 'weak covalent bonds'. Get the language right." } },
        { h: "Giant covalent (diamond, graphite, silicon dioxide)",
          body: ["Some covalent substances form giant structures, not small molecules.",
                 "<strong>Diamond:</strong> Each carbon forms 4 covalent bonds to other carbons in a giant 3D lattice. Very hard, very high melting point, doesn't conduct electricity.",
                 "<strong>Graphite:</strong> Each carbon forms 3 covalent bonds to other carbons in flat layers. The 4th outer electron is <strong>delocalised</strong> (free to move). This means graphite CAN conduct electricity. The layers slide over each other easily so graphite feels slippery (used in pencils).",
                 "<strong>Silicon dioxide (sand):</strong> Giant covalent structure, very high melting point, doesn't conduct."] },
        { h: "Metallic bonding",
          body: ["In metals, the atoms are arranged in a regular pattern. The outer electrons <strong>aren't held by any one atom</strong>, they're free to move around. We call this a 'sea of delocalised electrons'.",
                 "The positive metal ions are held in place by their attraction to this sea of negative electrons. That attraction is the metallic bond.",
                 "<strong>Properties of metals:</strong>",
                 "<ul><li><strong>Conduct electricity and heat</strong>, delocalised electrons can move and carry charge/energy</li><li><strong>High melting points</strong>, strong metallic bonds</li><li><strong>Malleable</strong> (can be bent and shaped), layers of ions can slide past each other</li></ul>"] }
      ],
      keyPoints: [
        "Atoms bond to achieve a full outer shell",
        "Ionic: metal + non-metal, electrons are transferred, makes ions",
        "Covalent: non-metal + non-metal, electrons are shared",
        "Metallic: metal + metal, electrons are delocalised in a 'sea'",
        "Ionic compounds have high melting points (strong lattice forces)",
        "Ionic compounds conduct only when molten or dissolved",
        "Simple molecules: weak forces BETWEEN molecules, low melting points",
        "Diamond: 4 bonds per carbon, hard, doesn't conduct",
        "Graphite: 3 bonds per carbon, delocalised electrons, CONDUCTS",
        "Metals conduct due to delocalised electrons"
      ],
      mistakes: [
        "Saying 'weak covalent bonds break' when something melts, it's the FORCES BETWEEN molecules that break, not the bonds inside",
        "Saying ionic compounds conduct when solid, they only conduct when molten or dissolved",
        "Confusing ionic and covalent, if there's a metal involved, it's ionic",
        "Saying diamond conducts electricity, it doesn't. Graphite does, because of its delocalised electrons"
      ]
    },

    c3: {
      intro: "Quantitative chemistry is the maths side of chemistry. You need to calculate masses, balance equations, and understand that nothing is created or destroyed in a chemical reaction.",
      sections: [
        { h: "Relative formula mass (Mr)",
          body: ["The relative formula mass of a compound is the sum of the relative atomic masses of all the atoms in its formula.",
                 "<strong>How to calculate:</strong>",
                 "<ul><li>Look up the relative atomic mass (Ar) of each element on the periodic table</li><li>Multiply each by how many atoms there are</li><li>Add them all up</li></ul>",
                 "<strong>Example 1: CO2</strong>. C = 12, O = 16. So Mr = 12 + (2 × 16) = 12 + 32 = 44.",
                 "<strong>Example 2: H2O</strong>. H = 1, O = 16. So Mr = (2 × 1) + 16 = 18.",
                 "<strong>Example 3: Ca(NO3)2</strong>. Watch the brackets, everything inside is multiplied by 2. Ca = 40, N = 14, O = 16. So Mr = 40 + 2 × (14 + 3×16) = 40 + 2 × 62 = 40 + 124 = 164."] },
        { h: "Conservation of mass",
          body: ["In any chemical reaction, <strong>the total mass of the products equals the total mass of the reactants</strong>. Atoms don't appear or disappear, they just rearrange.",
                 "This is why balanced equations have the same number of each type of atom on both sides.",
                 "<strong>Apparent mass changes in open containers</strong> can confuse students. If a gas is given off (like CO2 from a fizzing reaction), the mass of what's left appears to decrease. But the mass hasn't actually been lost, the gas escaped. If you trapped the gas, the total mass would still be the same."] },
        { h: "Balancing equations",
          body: ["A balanced equation has the same number of each type of atom on both sides.",
                 "<strong>How to balance:</strong>",
                 "<ul><li>Count each type of atom on both sides</li><li>If they don't match, put numbers in front of formulas to balance them</li><li>NEVER change a formula (e.g. you can't change H2O to H3O to balance)</li></ul>",
                 "<strong>Example:</strong> Mg + O2 → MgO",
                 "Left side: 1 Mg, 2 O. Right side: 1 Mg, 1 O. Oxygen isn't balanced.",
                 "Put 2 in front of MgO: Mg + O2 → 2MgO. Now: Left: 1 Mg, 2 O. Right: 2 Mg, 2 O. Magnesium isn't balanced.",
                 "Put 2 in front of Mg: <strong>2Mg + O2 → 2MgO</strong>. Now both sides have 2 Mg and 2 O. Balanced."] }
      ],
      keyPoints: [
        "Mr = sum of atomic masses of all atoms in the formula",
        "Brackets in formulas multiply everything inside",
        "Mass is conserved in every chemical reaction",
        "Balancing equations: change numbers in front of formulas, never the formulas themselves",
        "Both sides of a balanced equation must have equal numbers of each atom type"
      ],
      mistakes: [
        "Forgetting to multiply through brackets when calculating Mr",
        "Changing a formula (like H2O to H3O) to balance instead of using numbers in front",
        "Confusing atomic number with relative atomic mass",
        "Thinking mass is lost when a gas escapes, the mass left the container, it wasn't destroyed"
      ]
    },

    c4: {
      intro: "Chemical changes covers acids, alkalis, the reactivity series of metals, and electrolysis. This is a big topic with lots of marks available in Paper 1.",
      sections: [
        { h: "The pH scale",
          body: ["The pH scale runs from 0 to 14. It tells you how acidic or alkaline a solution is.",
                 "<ul><li><strong>pH 0-6: acidic</strong> (0-3 strong, 4-6 weak)</li><li><strong>pH 7: neutral</strong> (pure water)</li><li><strong>pH 8-14: alkaline</strong> (8-10 weak, 11-14 strong)</li></ul>",
                 "Acids contain H+ ions. Alkalis contain OH- ions. The more concentrated the H+ or OH-, the stronger the pH effect.",
                 "Universal indicator changes colour depending on pH. Red = strong acid. Yellow/orange = weak acid. Green = neutral. Blue = weak alkali. Purple = strong alkali."] },
        { h: "Neutralisation",
          body: ["When an acid reacts with an alkali, they neutralise each other to form a <strong>salt and water</strong>. The pH ends up around 7.",
                 "<strong>Acid + alkali → salt + water</strong>",
                 "Examples:",
                 "<ul><li>HCl + NaOH → NaCl + H2O</li><li>H2SO4 + 2KOH → K2SO4 + 2H2O</li></ul>",
                 "The salt depends on which acid you used:",
                 "<ul><li>Hydrochloric acid → chloride salts</li><li>Sulfuric acid → sulfate salts</li><li>Nitric acid → nitrate salts</li></ul>"] },
        { h: "Reactivity series",
          body: ["Some metals are more reactive than others. You need to learn this order:",
                 "<strong>K, Na, Ca, Mg, Al, (C), Zn, Fe, (H), Cu, Ag, Au</strong>",
                 "(Potassium, Sodium, Calcium, Magnesium, Aluminium, Carbon, Zinc, Iron, Hydrogen, Copper, Silver, Gold)",
                 "Carbon and hydrogen aren't metals but they appear in the list because we compare metals to them.",
                 "A common memory trick: <strong>Please Send Cats Monkeys And Cute Zebras In Heaven Cause Some Get Eaten</strong>. Use whatever works."] },
        { h: "Metals reacting with acids and water",
          body: ["<strong>Metals more reactive than hydrogen</strong> react with acids to give a salt and hydrogen gas. The hydrogen bubbles off as a colourless gas. Metals less reactive than hydrogen (like copper) don't react with acids.",
                 "Example: Mg + 2HCl → MgCl2 + H2",
                 "<strong>Most reactive metals (K, Na, Ca)</strong> react with cold water to give a metal hydroxide and hydrogen.",
                 "<strong>Less reactive metals</strong> (like iron) react only slowly with water and need heat or steam."] },
        { h: "Displacement reactions",
          body: ["A more reactive metal can <strong>displace</strong> (kick out) a less reactive metal from its compound.",
                 "Example: Magnesium is more reactive than copper. If you add magnesium to copper sulfate solution, the magnesium kicks the copper out:",
                 "<strong>Mg + CuSO4 → MgSO4 + Cu</strong>",
                 "You'd see the blue copper sulfate fade and brown copper metal form.",
                 "If you tried the reverse, copper added to magnesium sulfate, nothing would happen. Copper is less reactive than magnesium."] },
        { h: "Electrolysis",
          body: ["Electrolysis is using electricity to split an ionic compound into its elements.",
                 "You need an <strong>electrolyte</strong> (the molten ionic compound or solution) and two <strong>electrodes</strong> (rods that carry the current). The electrodes are usually made of inert graphite.",
                 "<ul><li><strong>Cathode</strong> = negative electrode. Positive ions go here, gain electrons, become atoms.</li><li><strong>Anode</strong> = positive electrode. Negative ions go here, lose electrons, become atoms.</li></ul>",
                 "Memory trick: <strong>P</strong>ositive ions go to <strong>N</strong>egative cathode (opposite charges attract).",
                 "Example: Electrolysis of molten lead bromide (PbBr2):",
                 "<ul><li>Cathode: Pb2+ ions gain electrons, become lead metal</li><li>Anode: Br- ions lose electrons, become bromine gas</li></ul>"] }
      ],
      keyPoints: [
        "Acid + alkali → salt + water (neutralisation)",
        "Hydrochloric acid makes chlorides, sulfuric makes sulfates, nitric makes nitrates",
        "Metals more reactive than hydrogen react with acids to give salt + hydrogen",
        "More reactive metals displace less reactive ones from compounds",
        "Cathode is negative, attracts positive ions, makes metal/hydrogen",
        "Anode is positive, attracts negative ions, makes non-metals"
      ],
      mistakes: [
        "Forgetting to balance equations with metals (e.g. forgetting the 2 in front of HCl when magnesium reacts)",
        "Mixing up cathode and anode, cathode is NEGATIVE",
        "Saying copper reacts with acid, it doesn't, it's below hydrogen",
        "Saying salt + water + something else, it's ALWAYS just salt + water for acid + alkali"
      ]
    },

    c5: {
      intro: "Energy changes are everywhere in chemistry. Some reactions release energy (you feel warm), others absorb it (you feel cold). Knowing the difference, and being able to draw the energy profile, is the core of this topic.",
      sections: [
        { h: "Exothermic and endothermic",
          body: ["Every chemical reaction either releases energy or absorbs it.",
                 "<strong>Exothermic reactions</strong> RELEASE energy to the surroundings. The temperature of the surroundings INCREASES. The energy 'exits' the reaction.",
                 "<strong>Endothermic reactions</strong> ABSORB energy from the surroundings. The temperature of the surroundings DECREASES. Energy 'enters' the reaction.",
                 "Easy memory trick: <strong>EXO</strong> = energy <strong>EX</strong>its (out). <strong>ENDO</strong> = energy <strong>EN</strong>ters (in)."] },
        { h: "Examples",
          body: ["<strong>Exothermic examples:</strong>",
                 "<ul><li>Combustion (burning fuel)</li><li>Neutralisation (acid + alkali)</li><li>Most oxidation reactions</li><li>Hand warmers</li><li>Self-heating cans</li></ul>",
                 "<strong>Endothermic examples:</strong>",
                 "<ul><li>Thermal decomposition (heating limestone, CaCO3 → CaO + CO2)</li><li>Photosynthesis (plants use light energy)</li><li>Sports injury cold packs (ammonium nitrate dissolving in water)</li><li>Citric acid + sodium hydrogencarbonate</li></ul>"] },
        { h: "Reaction profiles (energy diagrams)",
          body: ["A reaction profile is a diagram showing energy on the y-axis and the progress of the reaction on the x-axis.",
                 "<strong>For exothermic reactions:</strong> Products are LOWER than reactants. Energy has been released.",
                 "<strong>For endothermic reactions:</strong> Products are HIGHER than reactants. Energy has been absorbed.",
                 "Both types have an 'energy hump' in the middle. This is the <strong>activation energy</strong>, the minimum energy needed to start the reaction."],
          callout: { type: 'key', label: 'Activation energy', text: "Even an exothermic reaction needs energy to get started. That's why you need a spark to light a match, to give the reaction enough energy to overcome the activation energy barrier." } }
      ],
      keyPoints: [
        "Exothermic = energy released, temperature rises (think 'exits')",
        "Endothermic = energy absorbed, temperature drops (think 'enters')",
        "Combustion and neutralisation are always exothermic",
        "Thermal decomposition is always endothermic",
        "Reaction profiles show energy of reactants vs products",
        "Activation energy is the 'hump' on the profile, the energy needed to start the reaction"
      ],
      mistakes: [
        "Mixing up exo and endo, if temperature goes UP, it's exothermic",
        "Drawing reaction profiles with products higher when it's exothermic (it should be lower)",
        "Forgetting that even exothermic reactions need activation energy"
      ]
    },

    c6: {
      intro: "Rate of reaction is about how fast a chemical reaction happens. Some reactions are over in a flash (an explosion). Some take years (rust forming). Understanding what controls rate is one of the most useful things in chemistry.",
      sections: [
        { h: "What is rate?",
          body: ["The rate of a reaction is <strong>how quickly the reactants are used up</strong>, or how quickly the products are made.",
                 "Rate can be measured by:",
                 "<ul><li>How much gas is given off per second</li><li>How quickly a colour change happens</li><li>How quickly a solid disappears</li><li>How fast the mass changes</li></ul>"] },
        { h: "Collision theory",
          body: ["For a reaction to happen, particles must:",
                 "<ul><li><strong>Collide</strong> with each other</li><li>Have <strong>enough energy</strong> (more than the activation energy)</li></ul>",
                 "Anything that increases either the number of collisions OR the energy of collisions will speed up the reaction."] },
        { h: "Factors affecting rate",
          body: ["<strong>1. Temperature.</strong> Higher temperature = particles move faster = more collisions per second AND more collisions have enough energy. Rate INCREASES.",
                 "<strong>2. Concentration of solutions.</strong> More concentrated = more particles per unit volume = more collisions per second. Rate INCREASES.",
                 "<strong>3. Pressure of gases.</strong> Higher pressure squeezes gas particles closer together = more collisions per second. Rate INCREASES.",
                 "<strong>4. Surface area of solids.</strong> A powder has more surface area than a single lump (same mass). More particles exposed = more collisions. Rate INCREASES.",
                 "<strong>5. Catalysts.</strong> A catalyst speeds up a reaction by providing an alternative pathway with a lower activation energy. The catalyst itself is NOT used up."] },
        { h: "Catalysts in detail",
          body: ["A <strong>catalyst</strong> is a substance that speeds up a chemical reaction without being used up itself.",
                 "Key points about catalysts:",
                 "<ul><li>They don't change the products</li><li>They aren't used up, you have the same amount at the end</li><li>They work by providing an alternative pathway with lower activation energy</li><li>Different reactions need different catalysts</li><li><strong>Enzymes</strong> are biological catalysts (in your body)</li></ul>",
                 "Industrial example: iron is used as a catalyst in making ammonia (Haber process)."] }
      ],
      keyPoints: [
        "Rate measures how fast reactants are used or products are made",
        "Particles must collide with enough energy for a reaction to happen",
        "Increasing temperature, concentration, surface area, or pressure all speed up reactions",
        "Catalysts speed up reactions without being used up themselves",
        "Catalysts provide an alternative pathway with lower activation energy",
        "Enzymes are biological catalysts"
      ],
      mistakes: [
        "Saying a catalyst is 'used up', it isn't",
        "Saying surface area only matters for solids (it's actually only relevant for solids)",
        "For 3-mark rate questions: you need MORE collisions, MORE successful collisions, and explain WHY (more energy/closer/more particles)",
        "Confusing temperature with concentration, they're separate factors"
      ]
    },

    c7: {
      intro: "Organic chemistry sounds scary but at Foundation level it's mostly about crude oil and the hydrocarbons we get from it. Petrol, diesel, plastics, candles, gas, all come from crude oil. This is everyday science.",
      sections: [
        { h: "Crude oil and hydrocarbons",
          body: ["<strong>Crude oil</strong> is a finite resource found underground. It's a <strong>mixture</strong> of many different compounds, most of which are hydrocarbons.",
                 "A <strong>hydrocarbon</strong> is a compound made of ONLY hydrogen and carbon. Nothing else.",
                 "Crude oil isn't useful as it is, it's too thick and mixed. We separate it into useful fractions."] },
        { h: "Alkanes",
          body: ["The main hydrocarbons in crude oil are <strong>alkanes</strong>. Alkanes have:",
                 "<ul><li>Single bonds between all the carbons</li><li>General formula: <strong>CnH(2n+2)</strong></li><li>The first four are: methane (CH4), ethane (C2H6), propane (C3H8), butane (C4H10)</li></ul>",
                 "Learn the first four. You'll need them."],
          table: [["Name","Formula","Carbon atoms"],["Methane","CH4","1"],["Ethane","C2H6","2"],["Propane","C3H8","3"],["Butane","C4H10","4"]] },
        { h: "Fractional distillation",
          body: ["This is how we separate crude oil into useful fractions.",
                 "<strong>How it works:</strong>",
                 "<ul><li>Heat the crude oil so all of it evaporates</li><li>Send the vapour into a tall column that is HOT at the bottom and COOL at the top</li><li>Different hydrocarbons have different <strong>boiling points</strong>. Longer chain = higher boiling point.</li><li>As the vapour rises, each fraction condenses at the level where the temperature matches its boiling point</li><li>The fractions are tapped off at different heights</li></ul>",
                 "Fractions you should know (from bottom to top, longest to shortest chains):",
                 "<ul><li>Bitumen (roads)</li><li>Heavy fuel oil (ships, power stations)</li><li>Diesel (lorries, some cars)</li><li>Kerosene (jet planes)</li><li>Petrol (cars)</li><li>LPG / gases (heating, cooking)</li></ul>"] },
        { h: "Combustion",
          body: ["When hydrocarbons burn, they react with oxygen. This is called <strong>combustion</strong> and it's always exothermic.",
                 "<strong>Complete combustion</strong> (plenty of oxygen):",
                 "<strong>Hydrocarbon + oxygen → carbon dioxide + water</strong>",
                 "Example: CH4 + 2O2 → CO2 + 2H2O",
                 "<strong>Incomplete combustion</strong> (not enough oxygen):",
                 "Produces carbon monoxide (CO, a toxic gas) and soot (solid carbon), plus less energy.",
                 "This is why faulty boilers can be dangerous, if there's not enough air, they make CO, which is poisonous."],
          callout: { type: 'warn', label: 'Carbon monoxide', text: "CO is colourless, odourless, and toxic. It binds to your blood and stops it carrying oxygen. This is why we have CO detectors in homes." } }
      ],
      keyPoints: [
        "Hydrocarbons contain ONLY hydrogen and carbon",
        "Crude oil is a mixture of hydrocarbons",
        "Alkanes have single bonds, general formula CnH(2n+2)",
        "First four alkanes: methane, ethane, propane, butane",
        "Fractional distillation separates by boiling point",
        "Longer chain = higher boiling point",
        "Complete combustion: hydrocarbon + O2 → CO2 + H2O",
        "Incomplete combustion produces toxic carbon monoxide and soot"
      ],
      mistakes: [
        "Calling crude oil a 'compound', it's a MIXTURE",
        "Forgetting that fractional distillation works by boiling point",
        "Mixing up complete and incomplete combustion products",
        "Writing the wrong alkane formula, it's CnH(2n+2), not CnH(2n)"
      ]
    },

    c8: {
      intro: "Chemical analysis is about identifying and testing substances. At Foundation, this means understanding what 'pure' really means, and how chromatography separates mixtures.",
      sections: [
        { h: "Pure substances vs mixtures",
          body: ["In chemistry, 'pure' has a specific meaning. A <strong>pure substance</strong> contains only ONE element or ONE compound. Nothing else.",
                 "A <strong>mixture</strong> contains two or more substances physically mixed together (not chemically bonded).",
                 "Note: in everyday life, 'pure orange juice' might just mean 'no added sugar', but chemically, it's still a mixture of water, fructose, vitamins and other stuff.",
                 "<strong>Tests for purity:</strong> A pure substance has a SHARP, single melting point (and boiling point). An impure substance melts over a range of temperatures, and the melting point is usually LOWER than the pure substance would be."] },
        { h: "Formulations",
          body: ["A <strong>formulation</strong> is a useful mixture made by mixing substances in carefully measured amounts.",
                 "Examples: medicines (tablet contains the active drug plus other stuff to help it dissolve), paint (pigment + binder + solvent), alloys, cleaning products, fuels, fertilisers.",
                 "The key idea: a formulation is designed for a specific function. Each ingredient is there for a reason."] },
        { h: "Chromatography",
          body: ["Chromatography separates different substances in a mixture, often coloured ones like inks or dyes.",
                 "<strong>How paper chromatography works:</strong>",
                 "<ul><li>Draw a pencil line near the bottom of the chromatography paper (the start line)</li><li>Put a small spot of the mixture on the line</li><li>Stand the paper in a beaker with a little solvent at the bottom (below the spot, so the spot doesn't dissolve in)</li><li>The solvent travels up the paper, carrying the substances</li><li>Different substances move at different speeds, so they separate</li></ul>",
                 "<strong>Two 'phases':</strong>",
                 "<ul><li>The <strong>stationary phase</strong> is the paper (doesn't move)</li><li>The <strong>mobile phase</strong> is the solvent (moves up the paper)</li></ul>"] },
        { h: "Rf values",
          body: ["The <strong>Rf value</strong> tells you how far a substance moves up the paper compared to the solvent.",
                 "<strong>Rf = distance moved by the spot ÷ distance moved by the solvent</strong>",
                 "Rf is always a value between 0 and 1. It has no units.",
                 "Each substance has its own characteristic Rf value (in a given solvent). You can identify a substance by comparing its Rf to known values.",
                 "If a spot has Rf = 0, it didn't move at all. If Rf = 1, it moved with the solvent front."] }
      ],
      keyPoints: [
        "Pure substance: only ONE element or compound",
        "Mixture: two or more substances physically mixed",
        "Pure substances have ONE sharp melting point; impure melt over a range",
        "Formulations: useful mixtures with measured ingredients",
        "Chromatography: paper = stationary phase, solvent = mobile phase",
        "Rf = distance moved by spot ÷ distance moved by solvent",
        "Rf is always between 0 and 1, no units"
      ],
      mistakes: [
        "Confusing the everyday meaning of 'pure' with the chemistry meaning",
        "Drawing the start line in pen instead of pencil (ink would dissolve)",
        "Calculating Rf upside down, the SPOT distance is on top",
        "Forgetting that Rf has no units"
      ]
    },

    c9: {
      intro: "Chemistry of the atmosphere covers what's in the air, how it got that way, and the big issue of climate change. There's a fair bit of factual recall here so learn the percentages and the greenhouse gases.",
      sections: [
        { h: "Composition of the atmosphere",
          body: ["The Earth's atmosphere today is roughly:",
                 "<ul><li><strong>Nitrogen: 78%</strong> (about 4/5)</li><li><strong>Oxygen: 21%</strong> (about 1/5)</li><li><strong>Other gases: 1%</strong> (mainly argon, with small amounts of CO2 and water vapour)</li></ul>",
                 "Learn these. Examiners ask about them every year."] },
        { h: "How the atmosphere evolved",
          body: ["The atmosphere has changed dramatically over Earth's 4.6 billion year history.",
                 "<strong>Early atmosphere</strong> (over 3 billion years ago): mainly carbon dioxide from intense volcanic activity, with water vapour, nitrogen and small amounts of methane and ammonia. Very little oxygen.",
                 "<strong>What changed:</strong>",
                 "<ul><li>The Earth cooled, water vapour condensed to form oceans</li><li>CO2 dissolved in the oceans and then formed carbonate rocks</li><li>Algae and then plants evolved, doing photosynthesis. They took in CO2 and gave out O2</li><li>Over billions of years, oxygen built up and CO2 dropped, getting us to today's atmosphere</li></ul>"] },
        { h: "Greenhouse gases and climate change",
          body: ["Some gases in the atmosphere trap heat. They're called <strong>greenhouse gases</strong>.",
                 "<strong>The main greenhouse gases:</strong>",
                 "<ul><li>Carbon dioxide (CO2)</li><li>Methane (CH4)</li><li>Water vapour (H2O)</li></ul>",
                 "<strong>How the greenhouse effect works:</strong>",
                 "<ul><li>Short-wave radiation from the sun passes through the atmosphere and warms the Earth</li><li>The Earth re-emits this energy as long-wave (infrared) radiation</li><li>Greenhouse gases absorb this infrared radiation, trapping the heat</li><li>Some heat escapes, but more is trapped if there are more greenhouse gases</li></ul>"] },
        { h: "Why CO2 is rising",
          body: ["Human activities since the industrial revolution have INCREASED the amount of CO2 in the atmosphere.",
                 "<strong>Main sources of extra CO2:</strong>",
                 "<ul><li>Burning fossil fuels (coal, oil, gas) for energy and transport</li><li>Cement manufacture</li><li>Deforestation (trees absorb CO2, so cutting them down means less is absorbed)</li></ul>",
                 "<strong>Main source of extra methane:</strong>",
                 "<ul><li>Livestock farming (cows release methane)</li><li>Rice paddies</li><li>Decomposing rubbish in landfills</li></ul>",
                 "<strong>Consequences of climate change:</strong>",
                 "<ul><li>Rising global temperatures</li><li>Melting ice caps and rising sea levels</li><li>More extreme weather (storms, droughts, floods)</li><li>Changes in habitats and species ranges</li></ul>"] }
      ],
      keyPoints: [
        "Atmosphere is 78% nitrogen, 21% oxygen, 1% other",
        "Early atmosphere was mostly CO2 from volcanoes",
        "Oxygen came from photosynthesis by algae and plants",
        "Greenhouse gases: CO2, methane, water vapour",
        "Greenhouse gases absorb infrared radiation and trap heat",
        "Human activities (burning fossil fuels, farming, deforestation) increase greenhouse gases",
        "Climate change causes rising temperatures, sea level rise, extreme weather"
      ],
      mistakes: [
        "Getting the percentages wrong, it's 78% N, 21% O (not the other way round)",
        "Saying oxygen is the main greenhouse gas, it's CO2",
        "Confusing the greenhouse effect with the ozone hole, they're different things",
        "Saying greenhouse gases 'create' heat, they TRAP heat that's already there"
      ]
    },

    c10: {
      intro: "Using resources covers how we get the materials we use, including drinking water, recycled metals, and how we measure environmental impact. Lots of common-sense links to the real world here.",
      sections: [
        { h: "Potable water",
          body: ["<strong>Potable water</strong> means water that is safe to drink. It's not the same as pure water, tap water has dissolved minerals and chlorine in it, so it's not chemically pure, but it's safe.",
                 "<strong>In the UK</strong>, we mainly get potable water from rainwater that collects in lakes, rivers and reservoirs.",
                 "<strong>How tap water is made potable:</strong>",
                 "<ul><li>Filter water through beds of sand and gravel to remove solids</li><li>Sterilise the water using chlorine (or sometimes ozone or UV light) to kill microbes</li></ul>",
                 "<strong>In dry countries</strong>, sea water has to be desalinated (salt removed). This is done by distillation or reverse osmosis. Both use a lot of energy, which is why it's expensive."] },
        { h: "Waste water treatment",
          body: ["Used water from homes (sewage), farms, and industry needs to be treated before it can go back into rivers.",
                 "<strong>Sewage treatment steps:</strong>",
                 "<ul><li>Screening to remove large solids and grit</li><li>Settling out: the solid 'sludge' sinks to the bottom, the liquid 'effluent' is on top</li><li>The sludge is digested by anaerobic bacteria (no oxygen)</li><li>The effluent is treated with aerobic bacteria (with oxygen) to break down organic matter</li></ul>",
                 "Treated effluent is safe to release into rivers."] },
        { h: "Life Cycle Assessment (LCA)",
          body: ["An LCA looks at the <strong>environmental impact</strong> of a product over its whole life. It has four stages:",
                 "<ul><li><strong>Raw materials:</strong> Where do they come from? How much environmental damage to extract?</li><li><strong>Manufacturing:</strong> How much energy? What pollution?</li><li><strong>Use:</strong> Does it use energy or other resources while you're using it?</li><li><strong>Disposal:</strong> Can it be recycled? Will it sit in landfill?</li></ul>",
                 "Note: cost in money is NOT part of an LCA, only environmental impact."] },
        { h: "Reduce, reuse, recycle",
          body: ["The three Rs (in order of preference):",
                 "<ul><li><strong>Reduce:</strong> use less stuff in the first place</li><li><strong>Reuse:</strong> use the same thing again (refillable bottle)</li><li><strong>Recycle:</strong> turn the material into something new</li></ul>",
                 "<strong>Advantages of recycling metals:</strong>",
                 "<ul><li>Saves natural resources (less mining)</li><li>Uses less energy than extracting new metal from ore</li><li>Reduces CO2 emissions</li><li>Reduces landfill waste</li></ul>",
                 "<strong>Disadvantages of recycling:</strong>",
                 "<ul><li>Sorting different metals is difficult and labour-intensive</li><li>Collection has its own costs and emissions</li><li>Some metals can't be mixed when recycled</li></ul>"] }
      ],
      keyPoints: [
        "Potable water = safe to drink (not necessarily pure)",
        "UK potable water: filter + chlorinate",
        "Desalination of sea water uses lots of energy",
        "Sewage treated by screening, settling, anaerobic and aerobic digestion",
        "Life Cycle Assessment looks at environmental impact across 4 stages",
        "Cost in money is NOT part of an LCA",
        "Reduce > reuse > recycle (in that order)",
        "Recycling metals saves energy and resources but sorting is hard"
      ],
      mistakes: [
        "Saying potable means pure, it means SAFE TO DRINK",
        "Including cost in an LCA, LCAs are about environment, not money",
        "Saying recycling has no downsides, sorting and collection have costs",
        "Forgetting that REDUCE is more important than recycle"
      ]
    }
  };

  const questions = [
    { id: 'c1-1', topic: 'c1', type: 'mcq', marks: 1,
      text: 'Which sub-atomic particle has no electrical charge?',
      options: ['Proton', 'Neutron', 'Electron', 'Ion'],
      answer: 1,
      optionFeedback: [
        "Protons are positively charged (+1). Look back at the subatomic particles table.",
        "Correct. Neutrons have no charge. Protons are +1, electrons are -1, neutrons are neutral (the name's a clue).",
        "Electrons are negatively charged (-1). Try the subatomic particles section again.",
        "An ion isn't a sub-atomic particle, it's an atom that has gained or lost electrons. The three sub-atomic particles are protons, neutrons, electrons."
      ],
      teach: "Protons are +1, neutrons are 0, electrons are -1. This is fundamental, get the relative charges memorised early." },
    { id: 'c1-2', topic: 'c1', type: 'mcq', marks: 1,
      text: 'An atom of an element has 17 protons. What is the element?',
      options: ['Oxygen', 'Sulfur', 'Chlorine', 'Argon'],
      answer: 2,
      optionFeedback: [
        "Oxygen has 8 protons (atomic number 8). Look at the periodic table.",
        "Sulfur has 16 protons (atomic number 16), close, but not 17.",
        "Correct. The atomic number tells you the number of protons. Element with atomic number 17 is chlorine (Cl).",
        "Argon has 18 protons (atomic number 18), one too many."
      ],
      teach: "Atomic number = number of protons = position on the periodic table. Always check the periodic table, it's allowed in the exam." },
    { id: 'c1-3', topic: 'c1', type: 'mcq', marks: 1,
      text: 'Which group of the periodic table contains the noble gases?',
      options: ['Group 1', 'Group 2', 'Group 7', 'Group 0'],
      answer: 3,
      optionFeedback: [
        "Group 1 is the alkali metals (lithium, sodium, etc.), reactive, not noble.",
        "Group 2 is the alkaline earth metals (magnesium, calcium, etc.).",
        "Group 7 is the halogens (chlorine, bromine, etc.), very reactive non-metals.",
        "Correct. Group 0 (sometimes called Group 18) contains the noble gases: helium, neon, argon, krypton. They have full outer shells, which is why they're unreactive."
      ],
      teach: "Noble gases are in Group 0 because they have a full outer shell, they don't 'need' any more electrons, so they don't react." },
    { id: 'c1-4', topic: 'c1', type: 'short', marks: 2,
      text: 'Define what is meant by an "isotope".',
      markScheme: 'Atoms of the same element (1 mark) that have different numbers of neutrons (1 mark). Also acceptable: same atomic number but different mass number.',
      teach: "Same element = same protons. Isotopes only differ in their NEUTRONS. Examples: carbon-12 and carbon-14 are both carbon but carbon-14 has 2 extra neutrons." },
    { id: 'c1-5', topic: 'c1', type: 'short', marks: 3,
      text: 'Sodium and potassium are both in Group 1. Explain why potassium is MORE reactive than sodium.',
      markScheme: 'Potassium has more electron shells / outer electron is further from the nucleus (1 mark). The outer electron is held less strongly / weaker attraction to the nucleus (1 mark). So the outer electron is lost more easily during reactions (1 mark).',
      teach: "Going DOWN Group 1, reactivity INCREASES. The reason is always about the outer electron being further from the nucleus = weaker pull = easier to lose." },
    { id: 'c1-6', topic: 'c1', type: 'mcq', marks: 1,
      text: 'What is the electron arrangement of an oxygen atom (atomic number 8)?',
      options: ['2,6', '2,8', '6,2', '8,0'],
      answer: 0,
      optionFeedback: [
        "Correct. Fill shells in order: 2 in the first, then up to 8 in the second. Oxygen has 8 electrons total: 2 in the first shell, 6 in the second.",
        "2,8 would be 10 electrons, which is neon, not oxygen.",
        "You can't have 6 in the first shell, the first shell only holds 2 maximum.",
        "You can't have 8 in the first shell, the first shell only holds 2 maximum."
      ],
      teach: "Shells fill in order. First shell holds 2 max, then second and third hold 8 max each. Add the electrons one shell at a time." },

    { id: 'c2-1', topic: 'c2', type: 'mcq', marks: 1,
      text: 'Ionic bonds form between which types of element?',
      options: ['Two metals', 'A metal and a non-metal', 'Two non-metals', 'Two noble gases'],
      answer: 1,
      optionFeedback: [
        "Two metals form metallic bonds (delocalised electrons), not ionic bonds.",
        "Correct. Metal + non-metal = ionic. The metal loses electrons, the non-metal gains them. Opposite charges attract.",
        "Two non-metals form covalent bonds (sharing electrons), not ionic bonds.",
        "Noble gases already have full outer shells, so they don't usually bond at all."
      ],
      teach: "Three bond types, three combinations: metal+metal = metallic. metal+non-metal = ionic. non-metal+non-metal = covalent." },
    { id: 'c2-2', topic: 'c2', type: 'mcq', marks: 1,
      text: 'Why do ionic compounds have high melting points?',
      options: ['They contain many atoms', 'Strong electrostatic forces hold the ions together in a giant lattice', 'They are made of metals', 'They conduct electricity'],
      answer: 1,
      optionFeedback: [
        "Number of atoms doesn't determine melting point. Many compounds have lots of atoms but low melting points.",
        "Correct. The giant ionic lattice has billions of strong electrostatic attractions between positive and negative ions. It takes a LOT of energy to overcome these.",
        "Ionic compounds aren't 'made of metals', they contain a metal AND a non-metal (combined as ions).",
        "Conducting electricity is a separate property and doesn't cause a high melting point."
      ],
      teach: "Always link high melting point of ionic compounds to: STRONG electrostatic forces in a GIANT lattice. Both words matter for full marks." },
    { id: 'c2-3', topic: 'c2', type: 'short', marks: 2,
      text: 'Explain why graphite can conduct electricity but diamond cannot. Both are made of pure carbon.',
      markScheme: 'In graphite, each carbon atom forms 3 bonds, leaving one delocalised electron that is free to move (1 mark). In diamond, each carbon forms 4 bonds so there are no free electrons (1 mark).',
      teach: "Same element, different structures. Graphite: 3 bonds, 1 free electron, CONDUCTS. Diamond: 4 bonds, no free electrons, doesn't conduct." },
    { id: 'c2-4', topic: 'c2', type: 'mcq', marks: 1,
      text: 'In metallic bonding, what holds the metal atoms together?',
      options: ['Shared pairs of electrons', 'Attraction between positive metal ions and a "sea" of delocalised electrons', 'Ionic bonds', 'Strong gravity'],
      answer: 1,
      optionFeedback: [
        "Shared pairs of electrons describes covalent bonding, not metallic.",
        "Correct. Metals lose their outer electrons, which become delocalised. The positive metal ions are held by attraction to this sea of electrons.",
        "Ionic bonds happen between metals and non-metals, not between metal atoms.",
        "Gravity is far too weak to be relevant on the atomic scale."
      ],
      teach: "Metallic bonding = positive metal ions + sea of delocalised electrons. The delocalised electrons let metals conduct electricity." },
    { id: 'c2-5', topic: 'c2', type: 'short', marks: 2,
      text: 'Why do simple molecular substances (like H₂O or CO₂) have low melting and boiling points?',
      markScheme: 'The intermolecular forces between molecules are weak (1 mark). Only a small amount of energy is needed to overcome these forces (1 mark). Note: the covalent bonds inside the molecules are strong, but these are NOT broken when the substance melts.',
      teach: "Be careful with language: COVALENT BONDS are strong. The FORCES BETWEEN molecules are weak. When you melt water, you don't break the H-O bonds, you only overcome the forces between the H2O molecules." },

    { id: 'c3-1', topic: 'c3', type: 'mcq', marks: 1,
      text: 'What is the relative formula mass (Mr) of carbon dioxide, CO₂? (C=12, O=16)',
      options: ['28', '32', '44', '60'],
      answer: 2,
      optionFeedback: [
        "28 would be C + O = 12 + 16. You missed the second oxygen.",
        "32 is two oxygens (2 × 16) but you've forgotten the carbon.",
        "Correct. C + 2O = 12 + (2 × 16) = 12 + 32 = 44.",
        "60 is too high. Recount: 12 (one carbon) + 32 (two oxygens) = 44."
      ],
      teach: "When calculating Mr, count EVERY atom. CO2 has 1 carbon AND 2 oxygens. Multiply each by its atomic mass, then add." },
    { id: 'c3-2', topic: 'c3', type: 'mcq', marks: 1,
      text: 'What is the Mr of water (H₂O)? (H=1, O=16)',
      options: ['17', '18', '20', '34'],
      answer: 1,
      optionFeedback: [
        "17 would be 1 hydrogen + 1 oxygen. But water has 2 hydrogens.",
        "Correct. (2 × 1) + 16 = 2 + 16 = 18.",
        "Where did 20 come from? Recount: 2 hydrogens (2) + 1 oxygen (16) = 18.",
        "34 would be 2 oxygens and 2 hydrogens (32 + 2). But water only has ONE oxygen."
      ],
      teach: "The small number after an element is how many atoms of that element are in the molecule. H2O has 2 H and 1 O." },
    { id: 'c3-3', topic: 'c3', type: 'short', marks: 1,
      text: 'State the law of conservation of mass.',
      markScheme: 'The total mass of products in a chemical reaction is equal to the total mass of the reactants (1 mark). Also accept: mass is not created or destroyed in a chemical reaction.',
      teach: "Atoms don't appear or disappear, they just rearrange. Every balanced equation reflects this." },
    { id: 'c3-4', topic: 'c3', type: 'mcq', marks: 1,
      text: 'Balance this equation: __ Mg + O₂ → __ MgO',
      options: ['1, 1', '2, 2', '2, 1', '1, 2'],
      answer: 1,
      optionFeedback: [
        "1 Mg + 1 O2 → 1 MgO has 2 oxygens on the left but only 1 on the right. Not balanced.",
        "Correct. 2Mg + O2 → 2MgO. Each side: 2 Mg, 2 O. Balanced.",
        "2 Mg + 1 O2 → 1 MgO has 2 Mg on left but only 1 Mg on right. Not balanced.",
        "1 Mg + 1 O2 → 2 MgO has 1 Mg on left, 2 Mg on right. Not balanced."
      ],
      teach: "To balance: count each type of atom on both sides. Add numbers in front (NEVER change a formula) until both sides match." },

    { id: 'c4-1', topic: 'c4', type: 'mcq', marks: 1,
      text: 'A solution has a pH of 2. What does this tell you?',
      options: ['It is a strong alkali', 'It is a weak alkali', 'It is a strong acid', 'It is neutral'],
      answer: 2,
      optionFeedback: [
        "Strong alkalis are pH 11-14, not pH 2. Low pH means acidic.",
        "Alkalis are pH 8+. pH 2 is acidic, not alkaline.",
        "Correct. pH 0-3 = strong acid. pH 2 is well within that range.",
        "Neutral is pH 7. pH 2 is well below that."
      ],
      teach: "pH 0-3 = strong acid. 4-6 = weak acid. 7 = neutral. 8-10 = weak alkali. 11-14 = strong alkali. Lower number = more acidic." },
    { id: 'c4-2', topic: 'c4', type: 'mcq', marks: 1,
      text: 'Hydrochloric acid + sodium hydroxide → ?',
      options: ['Sodium + chloride + hydrogen', 'Sodium chloride + water', 'Salt + hydrogen', 'Sodium hydroxide chloride'],
      answer: 1,
      optionFeedback: [
        "You don't get loose sodium or chloride from neutralisation, you get sodium chloride (salt) and water.",
        "Correct. Acid + alkali → salt + water. ALWAYS. The salt is sodium chloride (NaCl), the water is H2O.",
        "Hydrogen comes from acid + metal, not acid + alkali. Acid + alkali = salt + WATER.",
        "Sodium hydroxide chloride isn't a real compound. You're just mashing the names together."
      ],
      teach: "Burn this into your brain: acid + alkali → salt + water. Always. No exceptions. No hydrogen." },
    { id: 'c4-3', topic: 'c4', type: 'short', marks: 3,
      text: 'Magnesium reacts vigorously with hydrochloric acid, but copper does not react at all. Explain why.',
      markScheme: 'Magnesium is more reactive than hydrogen (1 mark) so it can displace hydrogen from the acid (1 mark). Copper is less reactive than hydrogen so it cannot displace it / no reaction occurs (1 mark).',
      teach: "Reactivity series check: metals ABOVE hydrogen react with acid. Metals BELOW hydrogen don't. Mg is above, Cu is below." },
    { id: 'c4-4', topic: 'c4', type: 'mcq', marks: 1,
      text: 'During electrolysis of molten lead bromide, what is produced at the cathode (negative electrode)?',
      options: ['Bromine gas', 'Lead metal', 'Hydrogen', 'Oxygen'],
      answer: 1,
      optionFeedback: [
        "Bromine is produced at the anode (positive electrode), not the cathode. Bromide ions are negative.",
        "Correct. The cathode is negative, so it attracts positive ions. Pb2+ ions gain electrons and become lead metal.",
        "Hydrogen isn't produced from molten lead bromide. (Hydrogen can be made from electrolysis of solutions, but this is the MOLTEN compound.)",
        "Oxygen isn't produced from molten lead bromide. There's no oxygen in the compound."
      ],
      teach: "Cathode = negative = attracts POSITIVE ions. Positive metal ions get electrons here and become atoms. Anode = positive = attracts NEGATIVE ions." },
    { id: 'c4-5', topic: 'c4', type: 'short', marks: 2,
      text: 'Name the salt and other product formed when sulfuric acid reacts with potassium hydroxide.',
      markScheme: 'Potassium sulfate (1 mark) and water (1 mark).',
      teach: "Sulfuric acid always makes a SULFATE salt. Hydrochloric makes chloride. Nitric makes nitrate. The metal in the alkali becomes the metal in the salt." },

    { id: 'c5-1', topic: 'c5', type: 'mcq', marks: 1,
      text: 'Which of these is an exothermic reaction?',
      options: ['Photosynthesis', 'Thermal decomposition of calcium carbonate', 'Combustion of methane', 'Dissolving ammonium nitrate'],
      answer: 2,
      optionFeedback: [
        "Photosynthesis is endothermic, plants absorb energy from sunlight.",
        "Thermal decomposition is endothermic, you have to heat the substance to make it decompose.",
        "Correct. Combustion (burning) is always exothermic, it releases lots of heat and light.",
        "Ammonium nitrate dissolving is endothermic, this is how cold packs work."
      ],
      teach: "EXOthermic = energy EXits = temperature goes UP. Combustion is the classic exothermic reaction." },
    { id: 'c5-2', topic: 'c5', type: 'short', marks: 2,
      text: 'A student dissolves a chemical in water. The temperature of the water drops from 20°C to 12°C. State whether this is exothermic or endothermic, and explain why.',
      markScheme: 'Endothermic (1 mark). The temperature decrease shows the reaction has taken in/absorbed energy from the surroundings (1 mark).',
      teach: "Temperature DROP = surroundings have LOST energy = the reaction has taken energy IN = endothermic. Temperature RISE = exothermic." },
    { id: 'c5-3', topic: 'c5', type: 'mcq', marks: 1,
      text: 'Which application uses an endothermic reaction?',
      options: ['Hand warmers', 'Self-heating cans', 'Sports injury cold packs', 'Burning fuel in a car'],
      answer: 2,
      optionFeedback: [
        "Hand warmers RELEASE heat (your hands feel warmer), that's exothermic.",
        "Self-heating cans release heat (the can warms up), exothermic.",
        "Correct. Cold packs absorb heat from your skin, that's why they feel cold. Endothermic.",
        "Burning fuel releases heat, definitely exothermic."
      ],
      teach: "If something gives out heat, it's exothermic. If something feels cold or absorbs heat, it's endothermic. Cold packs are the textbook endothermic example." },

    { id: 'c6-1', topic: 'c6', type: 'mcq', marks: 1,
      text: 'Which of these does NOT increase the rate of a reaction?',
      options: ['Increasing the temperature', 'Increasing the concentration of reactants', 'Adding a catalyst', 'Decreasing the surface area'],
      answer: 3,
      optionFeedback: [
        "Increasing temperature DOES increase rate (particles move faster, more successful collisions).",
        "Increasing concentration DOES increase rate (more particles in a given volume, more collisions).",
        "Adding a catalyst DOES increase rate (provides a pathway with lower activation energy).",
        "Correct. DECREASING surface area SLOWS the reaction down. To speed it up, you INCREASE surface area (e.g. use a powder instead of a lump)."
      ],
      teach: "Four ways to speed up a reaction: more temperature, more concentration, more surface area, add a catalyst. The trick word here is 'decreasing'." },
    { id: 'c6-2', topic: 'c6', type: 'short', marks: 3,
      text: 'Explain how increasing the temperature increases the rate of a chemical reaction.',
      markScheme: 'Particles have more kinetic energy / move faster (1 mark). So particles collide more frequently (1 mark). And a greater proportion of collisions have enough energy to react / exceed the activation energy (1 mark).',
      teach: "For 3-mark rate questions: ALL THREE points, more energy/faster, more collisions, more SUCCESSFUL collisions (over activation energy). Each idea is worth a mark." },
    { id: 'c6-3', topic: 'c6', type: 'mcq', marks: 1,
      text: 'What does a catalyst do?',
      options: ['It gets used up in the reaction', 'It increases the rate without being used up', 'It changes the products formed', 'It makes the reaction exothermic'],
      answer: 1,
      optionFeedback: [
        "A catalyst is NOT used up. That's one of its defining features.",
        "Correct. A catalyst speeds up the reaction by providing a lower-activation-energy pathway. It is regenerated and not used up.",
        "A catalyst doesn't change WHAT products you get, only how FAST you get them.",
        "A catalyst doesn't change whether the reaction is exothermic or endothermic, it just changes the speed."
      ],
      teach: "Catalyst = speeds up the reaction, NOT used up, doesn't change the products. It just provides an easier pathway." },

    { id: 'c7-1', topic: 'c7', type: 'mcq', marks: 1,
      text: 'Crude oil is...',
      options: ['A compound', 'An element', 'A mixture of hydrocarbons', 'A single fuel'],
      answer: 2,
      optionFeedback: [
        "Crude oil isn't a single compound, it contains many different compounds mixed together.",
        "Crude oil isn't an element, it contains lots of different substances.",
        "Correct. Crude oil is a MIXTURE of many different hydrocarbons. This is why we have to separate it before use.",
        "Crude oil isn't a fuel by itself, we have to refine it into useful fuels like petrol and diesel."
      ],
      teach: "Crude oil = MIXTURE of hydrocarbons. That word 'mixture' is the key. If it was one compound, we wouldn't need fractional distillation." },
    { id: 'c7-2', topic: 'c7', type: 'mcq', marks: 1,
      text: 'What is the general formula for the alkanes?',
      options: ['CnH2n', 'CnHn+2', 'CnH2n+2', 'C2nHn'],
      answer: 2,
      optionFeedback: [
        "CnH2n is the formula for alkenes, not alkanes. Different family.",
        "CnHn+2 doesn't work, try it with methane (n=1): would give CH3, but methane is CH4.",
        "Correct. CnH(2n+2). Methane (n=1): CH4. Ethane (n=2): C2H6. Propane (n=3): C3H8.",
        "C2nHn would give methane (n=1) as C2H1, clearly wrong."
      ],
      teach: "Memorise CnH(2n+2) for alkanes. Test it on methane: 1 carbon, so 2(1)+2 = 4 hydrogens. CH4. It checks out." },
    { id: 'c7-3', topic: 'c7', type: 'short', marks: 2,
      text: 'Name the two products formed when methane (CH₄) undergoes COMPLETE combustion.',
      markScheme: 'Carbon dioxide (1 mark) and water (1 mark).',
      teach: "Complete combustion of any hydrocarbon: CO2 + H2O. Plenty of oxygen needed. If oxygen is limited (incomplete), you get carbon monoxide and soot instead." },
    { id: 'c7-4', topic: 'c7', type: 'mcq', marks: 1,
      text: 'Fractional distillation separates the parts of crude oil based on differences in their...',
      options: ['Colour', 'Boiling points', 'Density', 'Reactivity'],
      answer: 1,
      optionFeedback: [
        "Colour doesn't separate hydrocarbons, many are similar in appearance.",
        "Correct. Different hydrocarbons have different boiling points (longer chains = higher boiling point). The column is hot at the bottom and cool at the top, so each fraction condenses at the level matching its boiling point.",
        "Density isn't what separates them in fractional distillation. It's all about boiling points.",
        "Reactivity isn't relevant, fractional distillation is a physical process, not a chemical one."
      ],
      teach: "Fractional distillation works on boiling points. The taller the column, the better the separation. Different fractions are tapped off at different heights." },

    { id: 'c8-1', topic: 'c8', type: 'mcq', marks: 1,
      text: 'Which of the following is a pure substance?',
      options: ['Sea water', 'Air', 'Distilled water', 'Crude oil'],
      answer: 2,
      optionFeedback: [
        "Sea water has salts dissolved in it, so it's a mixture.",
        "Air is a mixture of gases (nitrogen, oxygen, argon, etc.).",
        "Correct. Distilled water is pure H2O, just one compound, nothing else.",
        "Crude oil is a mixture of many hydrocarbons."
      ],
      teach: "Pure = ONE substance only. If it has more than one component, it's a mixture, regardless of how 'clean' or 'natural' it looks." },
    { id: 'c8-2', topic: 'c8', type: 'short', marks: 2,
      text: 'A pure substance has a sharp, single melting point. Describe what you would observe about the melting point of an impure substance.',
      markScheme: 'It melts over a range of temperatures (1 mark). The melting point is lower than the pure substance (1 mark).',
      teach: "Impurities mess things up, the substance melts over a RANGE and the melting point is LOWER. This is one of the classic tests for purity." },
    { id: 'c8-3', topic: 'c8', type: 'mcq', marks: 1,
      text: 'In paper chromatography, what is the Rf value calculated as?',
      options: ['Distance moved by spot ÷ distance moved by solvent', 'Distance moved by solvent ÷ distance moved by spot', 'Total distance × time', 'Mass of spot ÷ mass of solvent'],
      answer: 0,
      optionFeedback: [
        "Correct. Rf = distance moved by spot ÷ distance moved by solvent. Always between 0 and 1.",
        "You've got it upside down. The spot distance is on TOP, solvent distance on the bottom.",
        "Time isn't part of the Rf formula. It's just two distances.",
        "Mass isn't part of Rf. It's only about how far the spot and solvent have travelled."
      ],
      teach: "Rf = SPOT distance ÷ SOLVENT distance. Always between 0 and 1. No units. Used to identify substances." },

    { id: 'c9-1', topic: 'c9', type: 'mcq', marks: 1,
      text: 'What percentage of the atmosphere is oxygen?',
      options: ['78%', '21%', '50%', '1%'],
      answer: 1,
      optionFeedback: [
        "78% is the percentage of NITROGEN, not oxygen. Easy to mix up.",
        "Correct. Oxygen is 21% of the atmosphere, about a fifth.",
        "Not 50%. Oxygen is about 1/5 of the atmosphere, not half.",
        "1% is everything that's NOT nitrogen or oxygen (argon, CO2, water vapour)."
      ],
      teach: "Atmosphere: 78% N2, 21% O2, 1% other (mostly argon plus tiny CO2). Learn these numbers, they come up every year." },
    { id: 'c9-2', topic: 'c9', type: 'short', marks: 2,
      text: 'Name TWO greenhouse gases.',
      markScheme: 'Any two from: carbon dioxide (CO₂), methane (CH₄), water vapour (H₂O). 1 mark each.',
      teach: "Three main greenhouse gases: CO2, methane, water vapour. CO2 is the one most affected by human activity (burning fossil fuels)." },
    { id: 'c9-3', topic: 'c9', type: 'short', marks: 3,
      text: 'Describe how increased levels of carbon dioxide in the atmosphere could lead to climate change.',
      markScheme: 'CO₂ absorbs the heat / infrared radiation emitted from the Earth (1 mark). More CO₂ traps more heat in the atmosphere (1 mark). This causes global temperatures to rise / leads to climate change (1 mark).',
      teach: "Three steps: (1) CO2 absorbs infrared, (2) more CO2 means more heat trapped, (3) this raises global temperatures. Each step = 1 mark." },
    { id: 'c9-4', topic: 'c9', type: 'mcq', marks: 1,
      text: 'Which human activity releases the MOST carbon dioxide into the atmosphere?',
      options: ['Recycling', 'Burning fossil fuels', 'Eating meat', 'Driving electric cars'],
      answer: 1,
      optionFeedback: [
        "Recycling reduces CO2 emissions overall (saves energy), not a major source.",
        "Correct. Burning fossil fuels (coal, oil, gas) for energy, heat and transport is by far the biggest human source of CO2.",
        "Eating meat does have an environmental impact (mainly methane from livestock), but burning fossil fuels still releases more CO2 globally.",
        "Electric cars don't release CO2 from the tailpipe. (The electricity might come from fossil fuels, but that's covered under 'burning fossil fuels'.)"
      ],
      teach: "Burning fossil fuels = #1 source of human CO2 emissions. Coal, oil, and natural gas in power stations and engines." },

    { id: 'c10-1', topic: 'c10', type: 'mcq', marks: 1,
      text: 'What does "potable water" mean?',
      options: ['Water that is salty', 'Water that is safe to drink', 'Water from the sea', 'Water that has been boiled'],
      answer: 1,
      optionFeedback: [
        "Salty water isn't potable, it's actually undrinkable in large amounts.",
        "Correct. Potable means safe to drink. Tap water is potable. It's NOT pure (it has dissolved minerals and chlorine), but it's safe.",
        "Sea water is the opposite of potable, it needs desalination first.",
        "Boiling helps kill microbes but doesn't define 'potable'. UK tap water is treated with chlorine and filtration, not just boiling."
      ],
      teach: "Potable = safe to drink. Doesn't have to be PURE, tap water has dissolved minerals and chlorine but it's still potable." },
    { id: 'c10-2', topic: 'c10', type: 'short', marks: 2,
      text: 'Give ONE advantage and ONE disadvantage of recycling metals instead of extracting new metal from ore.',
      markScheme: 'Advantage (any one): saves natural resources / uses less energy / less mining damage / less CO₂ / cheaper. Disadvantage (any one): sorting different metals is difficult / collection costs money / quality may be lower / not all metals can be recycled together. 1 mark for each.',
      teach: "When asked for advantage AND disadvantage, give ONE of each, clearly. Don't waffle. The answer should be obvious, what's good vs what's hard." },
    { id: 'c10-3', topic: 'c10', type: 'mcq', marks: 1,
      text: 'A life cycle assessment (LCA) looks at the environmental impact of a product. Which stage is NOT part of an LCA?',
      options: ['Extracting raw materials', 'Manufacturing the product', 'How much the product costs to buy', 'Disposing of the product'],
      answer: 2,
      optionFeedback: [
        "Extracting raw materials IS part of an LCA, the first stage.",
        "Manufacturing IS part of an LCA, the second stage.",
        "Correct. LCAs only consider environmental impact, not money/cost. Cost is a financial measure, not environmental.",
        "Disposal IS part of an LCA, the final stage."
      ],
      teach: "LCA = ENVIRONMENTAL impact only. The four stages are raw materials, manufacturing, use, disposal. Cost in money isn't included." }
  ];

  return { topics, lessons, questions };
})();
